-- Generated by Level Director X v1.1.0 on gio feb 6 18:52:27 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B09']={}
	assets.spriteSheetData['B09'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['82c2318fd8ea49472c2e58147374e9bc_0']={file ='82c2318fd8ea49472c2e58147374e9bc.jpg',name='82c2318fd8ea49472c2e58147374e9bc_0',class='',aX=0.5,aY=0.5,width=564,height=1004,frame=0,spriteSheetName='82c2318fd8ea49472c2e58147374e9bc',frameCount=1,
		 }
	assets['B11Speciale_18']={file ='B11Speciale.png',name='B11Speciale_18',class='',aX=0.5,aY=0.5,width=64,height=32,frame=19,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_0']={file ='B09.png',name='B09_0',class='',aX=0.5,aY=0.5,width=64,height=32,frame=1,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_1']={file ='B09.png',name='B09_1',class='',aX=0.5,aY=0.5,width=64,height=32,frame=2,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_2']={file ='B09.png',name='B09_2',class='',aX=0.5,aY=0.5,width=64,height=32,frame=3,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_3']={file ='B09.png',name='B09_3',class='',aX=0.5,aY=0.5,width=64,height=32,frame=4,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_4']={file ='B09.png',name='B09_4',class='',aX=0.5,aY=0.5,width=64,height=32,frame=5,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_5']={file ='B09.png',name='B09_5',class='',aX=0.5,aY=0.5,width=64,height=32,frame=6,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_12']={file ='B09.png',name='B09_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_13']={file ='B09.png',name='B09_13',class='',aX=0.5,aY=0.5,width=64,height=32,frame=14,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_20']={file ='B09.png',name='B09_20',class='',aX=0.5,aY=0.5,width=64,height=32,frame=21,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['sopra19_0']={file ='sopra19.jpg',name='sopra19_0',class='',aX=0.5,aY=0.5,width=228,height=51,frame=0,spriteSheetName='sopra19',frameCount=1,
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level19' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='82c2318fd8ea49472c2e58147374e9bc_0',objType='LDImage',class='',width=348.945,height=523.417,x=146,y=299,xScale=0.618696*1,yScale=0.521332*1,assetName='82c2318fd8ea49472c2e58147374e9bc_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=34.8945,height=17.4472,x=131,y=386,xScale=0.545226*1,yScale=0.545226*1,assetName='B11Speciale_18',
		rotation=-90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='2',objType='LDImage',class='',width=34.8945,height=17.4472,x=148,y=386,xScale=0.545226*1,yScale=0.545226*1,assetName='B11Speciale_18',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='sopra19_0',objType='LDImage',class='',width=348.945,height=55.6131,x=145,y=12,xScale=1.53046*1,yScale=1.09045*1,assetName='sopra19_0',
		userProps = {},
		},
	{name='3',objType='LDImage',class='',width=34.8945,height=17.4472,x=94,y=393,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='4',objType='LDImage',class='',width=34.8945,height=17.4472,x=94,y=375,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='5',objType='LDImage',class='',width=54.5226,height=17.4472,x=139,y=358,xScale=0.851916*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='6',objType='LDImage',class='',width=34.8945,height=17.4472,x=184,y=393,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='7',objType='LDImage',class='',width=34.8945,height=17.4472,x=184,y=375,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='8',objType='LDImage',class='',width=34.8945,height=17.4472,x=94,y=410,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='9',objType='LDImage',class='',width=34.8945,height=17.4472,x=184,y=410,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='10',objType='LDImage',class='',width=34.8945,height=17.4472,x=34,y=328,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='11',objType='LDImage',class='',width=46.8894,height=17.4472,x=253,y=253,xScale=0.732648*1,yScale=0.545226*1,assetName='B09_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='12',objType='LDImage',class='',width=34.8945,height=17.4472,x=93,y=351,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_20',
		rotation=-30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='13',objType='LDImage',class='',width=34.8945,height=17.4472,x=186,y=351,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_20',
		rotation=-330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='14',objType='LDImage',class='',width=54.5226,height=17.4472,x=139,y=340,xScale=0.851916*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='15',objType='LDImage',class='',width=54.5226,height=17.4472,x=139,y=412,xScale=0.851916*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='16',objType='LDImage',class='',width=19.6281,height=17.4472,x=59,y=307,xScale=0.30669*1,yScale=0.545226*1,assetName='B09_0',
		userProps = {},
		},
	{name='17',objType='LDImage',class='',width=19.6281,height=17.4472,x=91,y=332,xScale=0.30669*1,yScale=0.545226*1,assetName='B09_0',
		rotation=-30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='18',objType='LDImage',class='',width=19.6281,height=17.4472,x=188,y=332,xScale=0.30669*1,yScale=0.545226*1,assetName='B09_0',
		rotation=30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='19',objType='LDImage',class='',width=25.0804,height=17.4472,x=231,y=297,xScale=0.391881*1,yScale=0.545226*1,assetName='B09_0',
		userProps = {},
		},
	{name='20',objType='LDImage',class='',width=44.7085,height=17.4472,x=135,y=264,xScale=0.698571*1,yScale=0.545226*1,assetName='B09_0',
		userProps = {},
		},
	{name='21',objType='LDImage',class='',width=44.7085,height=17.4472,x=114,y=227,xScale=0.698571*1,yScale=0.545226*1,assetName='B09_0',
		rotation=-45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='22',objType='LDImage',class='',width=44.7085,height=17.4472,x=158,y=227,xScale=0.698571*1,yScale=0.545226*1,assetName='B09_0',
		rotation=-315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='23',objType='LDImage',class='',width=43.9452,height=17.4472,x=135,y=186,xScale=0.686644*1,yScale=0.545226*1,assetName='B09_0',
		rotation=-90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='24',objType='LDImage',class='',width=19.6281,height=17.4472,x=75,y=261,xScale=0.30669*1,yScale=0.545226*1,assetName='B09_0',
		userProps = {},
		},
	{name='25',objType='LDImage',class='',width=40.3467,height=17.4472,x=206,y=249,xScale=0.630418*1,yScale=0.545226*1,assetName='B09_0',
		userProps = {},
		},
	{name='26',objType='LDImage',class='',width=21.9223,height=10.9612,x=279,y=268,xScale=0.342537*1,yScale=0.342538*1,assetName='B09_5',
		rotation=-18,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='27',objType='LDImage',class='',width=21.809,height=10.9045,x=305,y=254,xScale=0.340766*1,yScale=0.340766*1,assetName='B09_4',
		rotation=353,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='28',objType='LDImage',class='',width=21.809,height=10.9045,x=277,y=253,xScale=0.340766*1,yScale=0.340766*1,assetName='B09_13',
		rotation=-18,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='29',objType='LDImage',class='',width=21.809,height=10.9045,x=303,y=238,xScale=0.340766*1,yScale=0.340766*1,assetName='B09_3',
		rotation=-11,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='30',objType='LDImage',class='',width=21.809,height=10.9045,x=275,y=237,xScale=0.340766*1,yScale=0.340766*1,assetName='B09_2',
		rotation=346,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='31',objType='LDImage',class='',width=21.809,height=10.9045,x=301,y=224,xScale=0.340766*1,yScale=0.340766*1,assetName='B09_1',
		rotation=354,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='32',objType='LDImage',class='',width=21.809,height=10.9045,x=274,y=222,xScale=0.340766*1,yScale=0.340766*1,assetName='B09_0',
		rotation=348,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='33',objType='LDImage',class='',width=34.8945,height=17.4472,x=253,y=294,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='34',objType='LDImage',class='',width=34.8945,height=17.4472,x=253,y=329,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='35',objType='LDImage',class='',width=34.8945,height=17.4472,x=253,y=363,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='36',objType='LDImage',class='',width=43.6181,height=17.4472,x=33,y=367,xScale=0.681533*1,yScale=0.545226*1,assetName='B09_12',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='37',objType='LDImage',class='',width=40.3467,height=17.4472,x=60,y=336,xScale=0.630418*1,yScale=0.545226*1,assetName='B09_12',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='38',objType='LDImage',class='',width=42.5276,height=17.4472,x=60,y=376,xScale=0.664494*1,yScale=0.545226*1,assetName='B09_12',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='39',objType='LDImage',class='',width=34.8945,height=17.4472,x=118,y=282,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='40',objType='LDImage',class='',width=34.8945,height=17.4472,x=153,y=282,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='41',objType='LDImage',class='',width=22.5574,height=11.2787,x=116,y=245,xScale=0.35246*1,yScale=0.35246*1,assetName='B09_20',
		rotation=-45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='42',objType='LDImage',class='',width=22.5574,height=11.2787,x=157,y=246,xScale=0.35246*1,yScale=0.352458*1,assetName='B09_20',
		rotation=-315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='43',objType='LDImage',class='',width=34.8945,height=17.4472,x=300,y=341,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_3',
		rotation=-15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=34.8945,height=17.4472,x=300,y=323,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_3',
		rotation=-15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='45',objType='LDImage',class='',width=34.8945,height=17.4472,x=300,y=305,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_3',
		rotation=-15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='46',objType='LDImage',class='',width=34.8945,height=17.4472,x=121,y=323,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='47',objType='LDImage',class='',width=34.8945,height=17.4472,x=155,y=323,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='48',objType='LDImage',class='',width=34.8945,height=17.4472,x=136,y=298,xScale=0.545226*1,yScale=0.545226*1,assetName='B09_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='49',objType='LDImage',class='',width=42.5276,height=17.4472,x=232,y=327,xScale=0.664494*1,yScale=0.545226*1,assetName='B09_12',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='50',objType='LDImage',class='',width=41.4372,height=17.4472,x=232,y=369,xScale=0.647456*1,yScale=0.545226*1,assetName='B09_12',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

