-- Generated by Level Director X v1.1.0 on lun feb 10 23:07:49 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B05']={}
	assets.spriteSheetData['B05'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['B11Speciale_8']={file ='B11Speciale.png',name='B11Speciale_8',class='',aX=0.5,aY=0.5,width=64,height=32,frame=9,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B11Speciale_12']={file ='B11Speciale.png',name='B11Speciale_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['525c5fa9a8ee7ebd149cf88e17887342_0']={file ='525c5fa9a8ee7ebd149cf88e17887342.jpg',name='525c5fa9a8ee7ebd149cf88e17887342_0',class='',aX=0.5,aY=0.5,width=564,height=1002,frame=0,spriteSheetName='525c5fa9a8ee7ebd149cf88e17887342',frameCount=1,
		 }
	assets['B05_4']={file ='B05.png',name='B05_4',class='',aX=0.5,aY=0.5,width=64,height=32,frame=5,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_8']={file ='B05.png',name='B05_8',class='',aX=0.5,aY=0.5,width=64,height=32,frame=9,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_10']={file ='B05.png',name='B05_10',class='',aX=0.5,aY=0.5,width=64,height=32,frame=11,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_12']={file ='B05.png',name='B05_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_13']={file ='B05.png',name='B05_13',class='',aX=0.5,aY=0.5,width=64,height=32,frame=14,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_20']={file ='B05.png',name='B05_20',class='',aX=0.5,aY=0.5,width=64,height=32,frame=21,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level22' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='525c5fa9a8ee7ebd149cf88e17887342_0',objType='LDImage',class='',width=322.527,height=573,x=161,y=231,xScale=0.571856*1,yScale=0.571856*1,assetName='525c5fa9a8ee7ebd149cf88e17887342_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=263,y=205,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_12',
		rotation=41,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=259,y=167,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-32,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='3',objType='LDImage',class='',width=32,height=16,x=300,y=205,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=295,y=171,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=232,y=184,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-32,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=205,y=202,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-32,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=284,y=233,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=268,y=261,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='9',objType='LDImage',class='',width=32,height=16,x=186,y=232,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-92,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=241,y=282,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='11',objType='LDImage',class='',width=32,height=16,x=155,y=188,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		userProps = {},
		},
	{name='12',objType='LDImage',class='',width=32,height=16,x=175,y=266,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-47,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='13',objType='LDImage',class='',width=32,height=16,x=207,y=295,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='14',objType='LDImage',class='',width=32,height=16,x=151,y=290,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-44,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='15',objType='LDImage',class='',width=32,height=16,x=125,y=313,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-41,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=98,y=334,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-36,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=72,y=342,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-306,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='18',objType='LDImage',class='',width=32,height=16,x=183,y=319,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=316,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='19',objType='LDImage',class='',width=32,height=16,x=158,y=342,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=320,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=130,y=363,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=326,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=100,y=381,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=333,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='22',objType='LDImage',class='',width=32,height=16,x=65,y=388,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=7,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='23',objType='LDImage',class='',width=32,height=16,x=36,y=366,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=72,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='24',objType='LDImage',class='',width=30.5871,height=16,x=39,y=329,xScale=0.477923*1,yScale=0.5*1,assetName='B05_12',
		rotation=119,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='25',objType='LDImage',class='',width=25.628,height=16,x=54,y=303,xScale=0.400438*1,yScale=0.5*1,assetName='B05_12',
		rotation=123,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='26',objType='LDImage',class='',width=32,height=16,x=121,y=193,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		rotation=-19,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='27',objType='LDImage',class='',width=32,height=16,x=90,y=211,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		rotation=-43,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='28',objType='LDImage',class='',width=32,height=16,x=68,y=238,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		rotation=-58,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='29',objType='LDImage',class='',width=32,height=16,x=58,y=271,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		rotation=-88,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='30',objType='LDImage',class='',width=32,height=16,x=153,y=378,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		userProps = {},
		},
	{name='31',objType='LDImage',class='',width=32,height=16,x=188,y=372,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		rotation=341,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='32',objType='LDImage',class='',width=32,height=16,x=217,y=354,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='33',objType='LDImage',class='',width=32,height=16,x=238,y=327,xScale=0.5*1,yScale=0.5*1,assetName='B05_10',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='34',objType='LDImage',class='',width=32,height=16,x=158,y=312,xScale=0.5*1,yScale=0.5*1,assetName='B05_20',
		rotation=318,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='35',objType='LDImage',class='',width=32,height=16,x=102,y=356,xScale=0.5*1,yScale=0.5*1,assetName='B05_20',
		rotation=327,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='36',objType='LDImage',class='',width=32,height=16,x=221,y=170,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-32,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='37',objType='LDImage',class='',width=32,height=16,x=248,y=152,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-32,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='38',objType='LDImage',class='',width=32,height=16,x=275,y=135,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-32,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='39',objType='LDImage',class='',width=32,height=16,x=303,y=118,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-32,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='40',objType='LDImage',class='',width=32,height=16,x=306,y=232,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='41',objType='LDImage',class='',width=32,height=16,x=290,y=260,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='42',objType='LDImage',class='',width=32,height=16,x=194,y=186,xScale=0.5*1,yScale=0.5*1,assetName='B05_12',
		rotation=-32,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='43',objType='LDImage',class='',width=32,height=16,x=95,y=185,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=-30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=32,height=16,x=136,y=171,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=354,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='45',objType='LDImage',class='',width=32,height=16,x=64,y=213,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=-53,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='46',objType='LDImage',class='',width=32,height=16,x=42,y=249,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=-68,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='47',objType='LDImage',class='',width=32,height=16,x=36,y=287,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=-85,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='48',objType='LDImage',class='',width=32,height=16,x=178,y=167,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=351,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='49',objType='LDImage',class='',width=32,height=16,x=214,y=153,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=328,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='50',objType='LDImage',class='',width=32,height=16,x=248,y=131,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=328,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='51',objType='LDImage',class='',width=32,height=16,x=282,y=110,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=328,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='52',objType='LDImage',class='',width=32,height=16,x=24,y=321,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=-62,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='53',objType='LDImage',class='',width=32,height=16,x=14,y=356,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=-92,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='54',objType='LDImage',class='',width=32,height=16,x=24,y=392,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=-122,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='55',objType='LDImage',class='',width=32,height=16,x=57,y=412,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=181,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='56',objType='LDImage',class='',width=32,height=16,x=93,y=408,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=166,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='57',objType='LDImage',class='',width=32,height=16,x=127,y=399,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=166,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='58',objType='LDImage',class='',width=32,height=16,x=172,y=395,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=173,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='59',objType='LDImage',class='',width=32,height=16,x=212,y=381,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=153,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='60',objType='LDImage',class='',width=32,height=16,x=242,y=353,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=129,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='61',objType='LDImage',class='',width=32,height=16,x=262,y=320,xScale=0.5*1,yScale=0.5*1,assetName='B05_4',
		rotation=114,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='62',objType='LDImage',class='',width=28.4668,height=16,x=285,y=292,xScale=0.444794*1,yScale=0.5*1,assetName='B05_4',
		rotation=144,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='63',objType='LDImage',class='',width=29.4567,height=16,x=307,y=266,xScale=0.460261*1,yScale=0.5*1,assetName='B05_4',
		rotation=122,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='64',objType='LDImage',class='',width=32,height=16,x=123,y=253,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_8',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

