-- Generated by Level Director X v1.1.0 on mer dic 11 18:09:09 2019 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets['finestraFineL_0']={file ='finestraFineL.png',name='finestraFineL_0',class='',aX=0.5,aY=0.5,width=640,height=960,frame=0,spriteSheetName='finestraFineL',frameCount=1,
		 }
	assets['score_0']={file ='score.png',name='score_0',class='',aX=0.5,aY=0.5,width=640,height=80,frame=0,spriteSheetName='score',frameCount=1,
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='finestra' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='finestraFineL_0',objType='LDImage',class='',width=320,height=480,x=162,y=242,xScale=0.5*1,yScale=0.5*1,assetName='finestraFineL_0',
		userProps = {},
		},
	{name='score_0',objType='LDImage',class='',width=320,height=40,x=184,y=266,xScale=0.5*1,yScale=0.5*1,assetName='score_0',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	---- Rects ------------------------------------------------------------------------------------
	level.layers['Rects']={} 
	level.layers['Rects'].view=display.newGroup() 
	level.layers['Rects'].name='Rects' 
	if (level.parallaxEnabled) then
		level.layers['Rects'].speed={x=0,y=0}
		level.layers['Rects'].repeated=false
		level.layers['Rects'].cullingMethod=0
	else
		level.layers['Rects'].cullingMethod=0 
	end
	level.layers['Rects'].objects={} 
	objects = {
	{name='rect_1',objType='LDRectangle',class='',width=68.6667,height=69,x=254,y=346,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=34.3333,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=1/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		userProps = {},
		},
	{name='rect_2',objType='LDRectangle',class='',width=14.3333,height=3,x=159,y=161,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=7.16667,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		userProps = {},
		},
	{name='rect_3',objType='LDRectangle',class='',width=35.6667,height=32.6667,x=184,y=263,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=17.8333,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Rects'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Rects'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

