-- Generated by Level Director X v1.1.0 on lun gen 6 23:47:45 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['16_sunburn_spritesheet']={}
	assets.spriteSheetData['16_sunburn_spritesheet'].frames ={
		{x=0,y=0,width=100,height=100},
		{x=100,y=0,width=100,height=100},
		{x=200,y=0,width=100,height=100},
		{x=300,y=0,width=100,height=100},
		{x=400,y=0,width=100,height=100},
		{x=500,y=0,width=100,height=100},
		{x=600,y=0,width=100,height=100},
		{x=700,y=0,width=100,height=100},
		{x=0,y=100,width=100,height=100},
		{x=100,y=100,width=100,height=100},
		{x=200,y=100,width=100,height=100},
		{x=300,y=100,width=100,height=100},
		{x=400,y=100,width=100,height=100},
		{x=500,y=100,width=100,height=100},
		{x=600,y=100,width=100,height=100},
		{x=700,y=100,width=100,height=100},
		{x=0,y=200,width=100,height=100},
		{x=100,y=200,width=100,height=100},
		{x=200,y=200,width=100,height=100},
		{x=300,y=200,width=100,height=100},
		{x=400,y=200,width=100,height=100},
		{x=500,y=200,width=100,height=100},
		{x=600,y=200,width=100,height=100},
		{x=700,y=200,width=100,height=100},
		{x=0,y=300,width=100,height=100},
		{x=100,y=300,width=100,height=100},
		{x=200,y=300,width=100,height=100},
		{x=300,y=300,width=100,height=100},
		{x=400,y=300,width=100,height=100},
		{x=500,y=300,width=100,height=100},
		{x=600,y=300,width=100,height=100},
		{x=700,y=300,width=100,height=100},
		{x=0,y=400,width=100,height=100},
		{x=100,y=400,width=100,height=100},
		{x=200,y=400,width=100,height=100},
		{x=300,y=400,width=100,height=100},
		{x=400,y=400,width=100,height=100},
		{x=500,y=400,width=100,height=100},
		{x=600,y=400,width=100,height=100},
		{x=700,y=400,width=100,height=100},
		{x=0,y=500,width=100,height=100},
		{x=100,y=500,width=100,height=100},
		{x=200,y=500,width=100,height=100},
		{x=300,y=500,width=100,height=100},
		{x=400,y=500,width=100,height=100},
		{x=500,y=500,width=100,height=100},
		{x=600,y=500,width=100,height=100},
		{x=700,y=500,width=100,height=100},
		{x=0,y=600,width=100,height=100},
		{x=100,y=600,width=100,height=100},
		{x=200,y=600,width=100,height=100},
		{x=300,y=600,width=100,height=100},
		{x=400,y=600,width=100,height=100},
		{x=500,y=600,width=100,height=100},
		{x=600,y=600,width=100,height=100},
		{x=700,y=600,width=100,height=100},
		{x=0,y=700,width=100,height=100},
		{x=100,y=700,width=100,height=100},
		{x=200,y=700,width=100,height=100},
		{x=300,y=700,width=100,height=100},
		{x=400,y=700,width=100,height=100},
		{x=500,y=700,width=100,height=100},
		{x=600,y=700,width=100,height=100},
		{x=700,y=700,width=100,height=100},
		sheetContentWidth=800,
		sheetContentHeight=800
	}
	assets['16_sunburn_spritesheet_0']={file ='16_sunburn_spritesheet.png',name='16_sunburn_spritesheet_0',class='',width=100,height=100,frame=1,spriteSheetName='16_sunburn_spritesheet',frameCount=64,
		sequenceData={{name='firing',frames={ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61 },time =1300,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='firing',play=true },
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDrawMode("wireframe",false)
	level.name='fireBall' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	display.setDefault( "isAnchorClamped", false )
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='16_sunburn_spritesheet_0',objType='LDImage',class='',width=100,height=100,x=155,y=225,xScale=1*1,yScale=1*1,assetName='16_sunburn_spritesheet_0',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

