-- Generated by Level Director X v1.1.0 on mer feb 19 21:53:04 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B03']={}
	assets.spriteSheetData['B03'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['spazio21_0']={file ='spazio21.jpg',name='spazio21_0',class='',aX=0.5,aY=0.5,width=564,height=810,frame=0,spriteSheetName='spazio21',frameCount=1,
		 }
	assets['B03_8']={file ='B03.png',name='B03_8',class='',aX=0.5,aY=0.5,width=64,height=32,frame=9,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_10']={file ='B03.png',name='B03_10',class='',aX=0.5,aY=0.5,width=64,height=32,frame=11,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={16,0,32,16,-32,16,-32,-16,32,-16,32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_19']={file ='B03.png',name='B03_19',class='',aX=0.5,aY=0.5,width=64,height=32,frame=20,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,16,-32,16,-32,-16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_23']={file ='B03.png',name='B03_23',class='',aX=0.5,aY=0.5,width=64,height=32,frame=24,spriteSheetName='B03',frameCount=25,
		 }
	assets['static part ui 4_0']={file ='static part ui 4.png',name='static part ui 4_0',class='',aX=0.5,aY=0.5,width=320,height=480,frame=0,spriteSheetName='static part ui 4',frameCount=1,
		 }
	assets['B11Speciale_8']={file ='B11Speciale.png',name='B11Speciale_8',class='',aX=0.5,aY=0.5,width=64,height=32,frame=9,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B11Speciale_19']={file ='B11Speciale.png',name='B11Speciale_19',class='',aX=0.5,aY=0.5,width=64,height=32,frame=20,spriteSheetName='B11Speciale',frameCount=25,
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level21' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='spazio21_0',objType='LDImage',class='',width=320,height=480,x=160,y=240,xScale=0.567376*1,yScale=0.592593*1,assetName='spazio21_0',
		userProps = {},
		},
	{name='B03_8',objType='LDImage',class='',width=32,height=16,x=288,y=176,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_3',objType='LDImage',class='',width=32,height=16,x=128,y=176,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_4',objType='LDImage',class='',width=32,height=16,x=96,y=184,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='B03_5',objType='LDImage',class='',width=32,height=16,x=160,y=184,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='5' },},
		},
	{name='B03_6',objType='LDImage',class='',width=32,height=16,x=192,y=177,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_7',objType='LDImage',class='',width=32,height=16,x=224,y=184,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_9',objType='LDImage',class='',width=32,height=16,x=256,y=192,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_10',objType='LDImage',class='',width=32,height=16,x=32,y=176,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_11',objType='LDImage',class='',width=32,height=16,x=64,y=192,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_12',objType='LDImage',class='',width=32,height=16,x=64,y=144,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_15',objType='LDImage',class='',width=32,height=16,x=255,y=144,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_19',objType='LDImage',class='',width=32,height=16,x=13,y=208,xScale=0.5*1,yScale=0.5*1,assetName='B03_19',
		rotation=-345,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='B03_16',objType='LDImage',class='',width=32,height=16,x=307,y=208,xScale=0.5*1,yScale=0.5*1,assetName='B03_19',
		rotation=-15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='B03_17',objType='LDImage',class='',width=32,height=16,x=32,y=256,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_18',objType='LDImage',class='',width=32,height=16,x=17,y=304,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_20',objType='LDImage',class='',width=32,height=16,x=49,y=304,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_21',objType='LDImage',class='',width=32,height=16,x=33,y=328,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_22',objType='LDImage',class='',width=32,height=16,x=72,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='B03_23',objType='LDImage',class='',width=32,height=16,x=104,y=368,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {{name= 'vita', value='5' },},
		},
	{name='B03_24',objType='LDImage',class='',width=32,height=16,x=136,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='B03_25',objType='LDImage',class='',width=32,height=16,x=184,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='B03_26',objType='LDImage',class='',width=32,height=16,x=216,y=368,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {{name= 'vita', value='5' },},
		},
	{name='B03_27',objType='LDImage',class='',width=32,height=16,x=248,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='B03_28',objType='LDImage',class='',width=32,height=16,x=273,y=304,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_29',objType='LDImage',class='',width=32,height=16,x=304,y=304,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_30',objType='LDImage',class='',width=32,height=16,x=288,y=256,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_1',objType='LDImage',class='',width=32,height=16,x=33,y=304,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='B03_31',objType='LDImage',class='',width=32,height=16,x=288,y=328,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B03_2',objType='LDImage',class='',width=32,height=16,x=289,y=304,xScale=0.5*1,yScale=0.5*-1,assetName='B11Speciale_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='B03_13',objType='LDImage',class='',width=32,height=16,x=31,y=128,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='5' },},
		},
	{name='B03_14',objType='LDImage',class='',width=32,height=16,x=287,y=128,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='5' },},
		},
	{name='B03_33',objType='LDImage',class='',width=32,height=16,x=160,y=208,xScale=0.5*1,yScale=0.5*1,assetName='B03_19',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='B03_36',objType='LDImage',class='',width=32,height=16,x=256,y=168,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_37',objType='LDImage',class='',width=32,height=16,x=224,y=200,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_38',objType='LDImage',class='',width=32,height=16,x=96,y=200,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_39',objType='LDImage',class='',width=32,height=16,x=32,y=152,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_40',objType='LDImage',class='',width=32,height=16,x=288,y=152,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_41',objType='LDImage',class='',width=32,height=16,x=216,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_42',objType='LDImage',class='',width=32,height=16,x=104,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_43',objType='LDImage',class='',width=32,height=16,x=32,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_44',objType='LDImage',class='',width=32,height=16,x=288,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_32',objType='LDImage',class='',width=32,height=16,x=32,y=232,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_34',objType='LDImage',class='',width=32,height=16,x=288,y=232,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	{name='B03_35',objType='LDImage',class='',width=32,height=16,x=64,y=168,xScale=0.5*1,yScale=0.5*1,assetName='B03_10',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

