-- Generated by Level Director X v1.1.0 on lun feb 17 19:10:24 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B08']={}
	assets.spriteSheetData['B08'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['lena-voronina-maya-civilization_0']={file ='lena-voronina-maya-civilization.jpg',name='lena-voronina-maya-civilization_0',class='',aX=0.5,aY=0.5,width=1120,height=1600,frame=0,spriteSheetName='lena-voronina-maya-civilization',frameCount=1,
		 }
	assets['B11Speciale_0']={file ='B11Speciale.png',name='B11Speciale_0',class='',aX=0.5,aY=0.5,width=64,height=32,frame=1,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_0']={file ='B08.png',name='B08_0',class='',aX=0.5,aY=0.5,width=64,height=32,frame=1,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_1']={file ='B08.png',name='B08_1',class='',aX=0.5,aY=0.5,width=64,height=32,frame=2,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_2']={file ='B08.png',name='B08_2',class='',aX=0.5,aY=0.5,width=64,height=32,frame=3,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_3']={file ='B08.png',name='B08_3',class='',aX=0.5,aY=0.5,width=64,height=32,frame=4,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_9']={file ='B08.png',name='B08_9',class='',aX=0.5,aY=0.5,width=64,height=32,frame=10,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_12']={file ='B08.png',name='B08_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level13' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='sfondo',objType='LDImage',class='',width=320,height=480,x=160,y=241,xScale=0.285714*1,yScale=0.3*1,assetName='lena-voronina-maya-civilization_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=144,y=331,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=176,y=331,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='3',objType='LDImage',class='',width=32,height=16,x=210,y=322,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=238,y=306,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=82,y=307,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=110,y=323,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=64,y=244,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=64,y=276,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='9',objType='LDImage',class='',width=32,height=16,x=255,y=243,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=255,y=275,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='11',objType='LDImage',class='',width=32,height=15,x=46,y=276,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='12',objType='LDImage',class='',width=32,height=15,x=46,y=244,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='13',objType='LDImage',class='',width=32,height=15,x=274,y=275,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='14',objType='LDImage',class='',width=32,height=15,x=274,y=243,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='15',objType='LDImage',class='',width=32,height=16,x=27,y=244,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=27,y=276,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=27,y=180,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='18',objType='LDImage',class='',width=32,height=16,x=292,y=179,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='19',objType='LDImage',class='',width=32,height=16,x=292,y=275,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=292,y=243,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=8,y=276,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='22',objType='LDImage',class='',width=32,height=16,x=8,y=244,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='23',objType='LDImage',class='',width=32,height=16,x=8,y=148,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='24',objType='LDImage',class='',width=32,height=16,x=8,y=212,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='25',objType='LDImage',class='',width=32,height=16,x=8,y=180,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='26',objType='LDImage',class='',width=32,height=16,x=312,y=211,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='28',objType='LDImage',class='',width=32,height=16,x=312,y=243,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='27',objType='LDImage',class='',width=32,height=16,x=312,y=275,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='29',objType='LDImage',class='',width=32,height=16,x=312,y=179,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='30',objType='LDImage',class='',width=32,height=16,x=312,y=147,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='31',objType='LDImage',class='',width=32,height=16,x=54,y=311,xScale=0.5*1,yScale=0.5*1,assetName='B08_1',
		rotation=60,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='32',objType='LDImage',class='',width=32,height=16,x=70,y=339,xScale=0.5*1,yScale=0.5*1,assetName='B08_1',
		rotation=60,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='33',objType='LDImage',class='',width=32,height=16,x=100,y=357,xScale=0.5*1,yScale=0.5*1,assetName='B08_1',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='34',objType='LDImage',class='',width=32,height=16,x=132,y=357,xScale=0.5*1,yScale=0.5*1,assetName='B08_1',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='35',objType='LDImage',class='',width=26,height=16,x=161,y=357,xScale=0.40625*1,yScale=0.5*1,assetName='B08_1',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='36',objType='LDImage',class='',width=32,height=16,x=190,y=357,xScale=0.5*1,yScale=0.5*1,assetName='B08_1',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='37',objType='LDImage',class='',width=32,height=16,x=249,y=337,xScale=0.5*1,yScale=0.5*1,assetName='B08_1',
		rotation=-60,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='38',objType='LDImage',class='',width=32,height=16,x=265,y=309,xScale=0.5*1,yScale=0.5*1,assetName='B08_1',
		rotation=-60,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='39',objType='LDImage',class='',width=32,height=16,x=222,y=357,xScale=0.5*1,yScale=0.5*1,assetName='B08_1',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='40',objType='LDImage',class='',width=32,height=16,x=56,y=211,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_0',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='41',objType='LDImage',class='',width=32,height=16,x=264,y=211,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_0',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='42',objType='LDImage',class='',width=32,height=16,x=27,y=212,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='43',objType='LDImage',class='',width=32,height=16,x=292,y=211,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=32,height=16,x=64,y=180,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='45',objType='LDImage',class='',width=32,height=15,x=46,y=180,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='46',objType='LDImage',class='',width=32,height=16,x=255,y=179,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='47',objType='LDImage',class='',width=32,height=15,x=273,y=179,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='48',objType='LDImage',class='',width=32,height=16,x=35,y=155,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='49',objType='LDImage',class='',width=32,height=16,x=284,y=155,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		userProps = {},
		},
	{name='50',objType='LDImage',class='',width=32,height=15,x=87,y=229,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='51',objType='LDImage',class='',width=32,height=15,x=87,y=197,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='52',objType='LDImage',class='',width=32,height=15,x=235,y=197,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='53',objType='LDImage',class='',width=32,height=15,x=235,y=229,xScale=0.5*1,yScale=0.46875*1,assetName='B08_1',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='54',objType='LDImage',class='',width=32,height=16,x=152,y=222,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='55',objType='LDImage',class='',width=32,height=16,x=152,y=254,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='56',objType='LDImage',class='',width=32,height=16,x=168,y=222,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='57',objType='LDImage',class='',width=32,height=16,x=168,y=254,xScale=0.5*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='58',objType='LDImage',class='',width=21,height=16,x=142,y=278,xScale=0.328125*1,yScale=0.5*1,assetName='B08_2',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='59',objType='LDImage',class='',width=19,height=16,x=177,y=278,xScale=0.296875*1,yScale=0.5*1,assetName='B08_2',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='60',objType='LDImage',class='',width=26,height=16,x=160,y=283,xScale=0.40625*1,yScale=0.5*1,assetName='B08_2',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='61',objType='LDImage',class='',width=32,height=16,x=66,y=155,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='62',objType='LDImage',class='',width=32,height=16,x=252,y=155,xScale=0.5*1,yScale=0.5*1,assetName='B08_0',
		userProps = {},
		},
	{name='63',objType='LDImage',class='',width=32,height=16,x=17,y=310,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='64',objType='LDImage',class='',width=32,height=16,x=33,y=338,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='65',objType='LDImage',class='',width=32,height=16,x=49,y=366,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=-300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='66',objType='LDImage',class='',width=32,height=16,x=80,y=384,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='67',objType='LDImage',class='',width=32,height=16,x=112,y=384,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='68',objType='LDImage',class='',width=32,height=16,x=144,y=384,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='69',objType='LDImage',class='',width=32,height=16,x=287,y=337,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='70',objType='LDImage',class='',width=32,height=16,x=303,y=309,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='71',objType='LDImage',class='',width=32,height=16,x=271,y=365,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='72',objType='LDImage',class='',width=32,height=16,x=176,y=384,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='73',objType='LDImage',class='',width=32,height=16,x=240,y=384,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='74',objType='LDImage',class='',width=32,height=16,x=208,y=384,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

