-- Generated by Level Director X v1.1.0 on gio feb 20 00:20:32 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B08']={}
	assets.spriteSheetData['B08'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['roma20_0']={file ='roma20.jpg',name='roma20_0',class='',aX=0.5,aY=0.5,width=454,height=643,frame=0,spriteSheetName='roma20',frameCount=1,
		 }
	assets['B08_12']={file ='B08.png',name='B08_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,32,-16,32,16,-32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_21']={file ='B08.png',name='B08_21',class='',aX=0.5,aY=0.5,width=64,height=32,frame=22,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,32,-16,32,16,-32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_22']={file ='B08.png',name='B08_22',class='',aX=0.5,aY=0.5,width=64,height=32,frame=23,spriteSheetName='B08',frameCount=25,
		 }
	assets['B11Speciale_21']={file ='B11Speciale.png',name='B11Speciale_21',class='',aX=0.5,aY=0.5,width=64,height=32,frame=22,spriteSheetName='B11Speciale',frameCount=25,
		tipo='speciale',		
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,32,-16,32,16,-32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level20' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='roma20_2',objType='LDImage',class='',width=325,height=460.297,x=161,y=230,xScale=0.715859*1,yScale=0.715859*1,assetName='roma20_0',
		userProps = {},
		},
	{name='B08_1',objType='LDImage',class='',width=32,height=16,x=16,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_3',objType='LDImage',class='',width=32,height=16,x=48,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_4',objType='LDImage',class='',width=32,height=16,x=80,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_5',objType='LDImage',class='',width=32,height=16,x=112,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_6',objType='LDImage',class='',width=32,height=16,x=144,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_7',objType='LDImage',class='',width=32,height=16,x=176,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_8',objType='LDImage',class='',width=32,height=16,x=208,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_9',objType='LDImage',class='',width=32,height=16,x=272,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_10',objType='LDImage',class='',width=32,height=16,x=304,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_11',objType='LDImage',class='',width=32,height=16,x=240,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_15',objType='LDImage',class='',width=32,height=16,x=64,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_16',objType='LDImage',class='',width=32,height=16,x=96,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_17',objType='LDImage',class='',width=32,height=16,x=144,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_18',objType='LDImage',class='',width=32,height=16,x=176,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_19',objType='LDImage',class='',width=32,height=16,x=225,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_20',objType='LDImage',class='',width=32,height=16,x=257,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_21',objType='LDImage',class='',width=32,height=16,x=304,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_22',objType='LDImage',class='',width=32,height=16,x=16,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_23',objType='LDImage',class='',width=32,height=16,x=16,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_24',objType='LDImage',class='',width=32,height=16,x=64,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_25',objType='LDImage',class='',width=32,height=16,x=96,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_26',objType='LDImage',class='',width=32,height=16,x=144,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_27',objType='LDImage',class='',width=32,height=16,x=176,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_28',objType='LDImage',class='',width=32,height=16,x=225,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_29',objType='LDImage',class='',width=32,height=16,x=257,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_30',objType='LDImage',class='',width=32,height=16,x=304,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B08_12',
		userProps = {{name= 'vita', value='6' },},
		},
	{name='B08_31',objType='LDImage',class='',width=32,height=16,x=80,y=248,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_32',objType='LDImage',class='',width=32,height=16,x=160,y=248,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_33',objType='LDImage',class='',width=32,height=16,x=240,y=248,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_34',objType='LDImage',class='',width=32,height=16,x=80,y=207,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_35',objType='LDImage',class='',width=32,height=16,x=160,y=207,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_36',objType='LDImage',class='',width=32,height=16,x=240,y=207,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_37',objType='LDImage',class='',width=32,height=16,x=16,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_38',objType='LDImage',class='',width=32,height=16,x=48,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_39',objType='LDImage',class='',width=32,height=16,x=80,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_41',objType='LDImage',class='',width=32,height=16,x=144,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_42',objType='LDImage',class='',width=32,height=16,x=176,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_43',objType='LDImage',class='',width=32,height=16,x=208,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_44',objType='LDImage',class='',width=32,height=16,x=240,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_45',objType='LDImage',class='',width=32,height=16,x=272,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_46',objType='LDImage',class='',width=32,height=16,x=304,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		userProps = {},
		},
	{name='B08_47',objType='LDImage',class='',width=32,height=16,x=37,y=120,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		rotation=15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B08_48',objType='LDImage',class='',width=32,height=16,x=284,y=118,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		rotation=345,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B08_2',objType='LDImage',class='',width=32,height=16,x=37,y=140,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		rotation=15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B08_12',objType='LDImage',class='',width=32,height=16,x=284,y=138,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		rotation=345,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B08_13',objType='LDImage',class='',width=32,height=16,x=37,y=160,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		rotation=15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B08_14',objType='LDImage',class='',width=32,height=16,x=284,y=159,xScale=0.5*1,yScale=0.5*1,assetName='B08_21',
		rotation=345,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B08_40',objType='LDImage',class='',width=32,height=16,x=112,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_21',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

