-- Generated by Level Director X v1.1.0 on mar feb 11 01:01:18 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B01']={}
	assets.spriteSheetData['B01'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['24750_0']={file ='24750.jpg',name='24750_0',class='',aX=0.5,aY=0.5,width=1080,height=1920,frame=0,spriteSheetName='24750',frameCount=1,
		 }
	assets['B11Speciale_2']={file ='B11Speciale.png',name='B11Speciale_2',class='',aX=0.5,aY=0.5,width=64,height=32,frame=3,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B01_0']={file ='B01.png',name='B01_0',class='',aX=0.5,aY=0.5,width=64,height=32,frame=1,spriteSheetName='B01',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B01_1']={file ='B01.png',name='B01_1',class='',aX=0.5,aY=0.5,width=64,height=32,frame=2,spriteSheetName='B01',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B01_2']={file ='B01.png',name='B01_2',class='',aX=0.5,aY=0.5,width=64,height=32,frame=3,spriteSheetName='B01',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B01_5']={file ='B01.png',name='B01_5',class='',aX=0.5,aY=0.5,width=64,height=32,frame=6,spriteSheetName='B01',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B01_6']={file ='B01.png',name='B01_6',class='',aX=0.5,aY=0.5,width=64,height=32,frame=7,spriteSheetName='B01',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B01_8']={file ='B01.png',name='B01_8',class='',aX=0.5,aY=0.5,width=64,height=32,frame=9,spriteSheetName='B01',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B01_10']={file ='B01.png',name='B01_10',class='',aX=0.5,aY=0.5,width=64,height=32,frame=11,spriteSheetName='B01',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B01_12']={file ='B01.png',name='B01_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B01',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level23' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='24750_0',objType='LDImage',class='',width=325.938,height=579.444,x=160,y=275,xScale=0.301794*1,yScale=0.301794*1,assetName='24750_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=155,y=270,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_2',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=155,y=209,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='3',objType='LDImage',class='',width=32,height=16,x=189,y=218,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		rotation=30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='4',objType='LDImage',class='',width=34.7591,height=16,x=211,y=293,xScale=0.543111*1,yScale=0.5*1,assetName='B01_2',
		rotation=105,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=155,y=330,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=189,y=321,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		rotation=-30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=121,y=321,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		rotation=-330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=121,y=218,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		rotation=330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='9',objType='LDImage',class='',width=32,height=16,x=97,y=294,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		rotation=-285,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=98,y=244,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		rotation=285,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='11',objType='LDImage',class='',width=32,height=16,x=211,y=246,xScale=0.5*1,yScale=0.5*1,assetName='B01_2',
		rotation=75,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='12',objType='LDImage',class='',width=32,height=16,x=124,y=270,xScale=0.5*1,yScale=0.5*1,assetName='B01_1',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='13',objType='LDImage',class='',width=32,height=16,x=186,y=270,xScale=0.5*1,yScale=0.5*1,assetName='B01_1',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='14',objType='LDImage',class='',width=32,height=16,x=139,y=246,xScale=0.5*1,yScale=0.5*1,assetName='B01_1',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='15',objType='LDImage',class='',width=32,height=16,x=171,y=246,xScale=0.5*1,yScale=0.5*1,assetName='B01_1',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=171,y=294,xScale=0.5*1,yScale=0.5*1,assetName='B01_1',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=139,y=294,xScale=0.5*1,yScale=0.5*1,assetName='B01_1',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='18',objType='LDImage',class='',width=32,height=16,x=245,y=382,xScale=0.5*1,yScale=0.5*1,assetName='B01_5',
		userProps = {},
		},
	{name='19',objType='LDImage',class='',width=32,height=16,x=273,y=360,xScale=0.5*1,yScale=0.5*1,assetName='B01_5',
		rotation=285,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=213,y=364,xScale=0.5*1,yScale=0.5*1,assetName='B01_5',
		rotation=60,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=223,y=330,xScale=0.5*1,yScale=0.5*1,assetName='B01_5',
		rotation=146,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='22',objType='LDImage',class='',width=32,height=16,x=259,y=327,xScale=0.5*1,yScale=0.5*1,assetName='B01_5',
		rotation=-154,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='23',objType='LDImage',class='',width=24.1961,height=12.098,x=128,y=386,xScale=0.378064*1,yScale=0.378064*1,assetName='B01_6',
		rotation=255,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='24',objType='LDImage',class='',width=24.1961,height=12.098,x=148,y=404,xScale=0.378064*1,yScale=0.378064*1,assetName='B01_6',
		rotation=195,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='25',objType='LDImage',class='',width=24.1961,height=12.098,x=176,y=397,xScale=0.378064*1,yScale=0.378064*1,assetName='B01_6',
		rotation=135,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='26',objType='LDImage',class='',width=24.1961,height=12.098,x=133,y=356,xScale=0.378064*1,yScale=0.378064*1,assetName='B01_6',
		rotation=135,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='27',objType='LDImage',class='',width=24.1961,height=12.0981,x=163,y=347,xScale=0.378064*1,yScale=0.378065*1,assetName='B01_6',
		rotation=192,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='28',objType='LDImage',class='',width=24.1961,height=12.0981,x=185,y=369,xScale=0.378064*1,yScale=0.378065*1,assetName='B01_6',
		rotation=255,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='29',objType='LDImage',class='',width=25.5072,height=12.7536,x=53,y=201,xScale=0.39855*1,yScale=0.39855*1,assetName='B01_8',
		userProps = {},
		},
	{name='30',objType='LDImage',class='',width=25.5072,height=12.7536,x=78,y=219,xScale=0.39855*1,yScale=0.39855*1,assetName='B01_8',
		rotation=-289,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='31',objType='LDImage',class='',width=25.5072,height=12.7536,x=70,y=251,xScale=0.39855*1,yScale=0.39855*1,assetName='B01_8',
		rotation=-225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='32',objType='LDImage',class='',width=25.5072,height=12.7536,x=37,y=253,xScale=0.39855*1,yScale=0.39855*1,assetName='B01_8',
		rotation=-330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='33',objType='LDImage',class='',width=25.5072,height=12.7536,x=25,y=220,xScale=0.39855*1,yScale=0.39855*1,assetName='B01_8',
		rotation=-255,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='34',objType='LDImage',class='',width=28.0643,height=14.0321,x=35,y=296,xScale=0.438504*1,yScale=0.438504*1,assetName='B01_12',
		rotation=-43,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='35',objType='LDImage',class='',width=28.0643,height=14.0321,x=90,y=350,xScale=0.438504*1,yScale=0.438504*1,assetName='B01_12',
		rotation=135,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='36',objType='LDImage',class='',width=28.0643,height=14.0321,x=62,y=364,xScale=0.438504*1,yScale=0.438504*1,assetName='B01_12',
		rotation=171,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='37',objType='LDImage',class='',width=28.0643,height=14.0321,x=33,y=353,xScale=0.438504*1,yScale=0.438504*1,assetName='B01_12',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='38',objType='LDImage',class='',width=28.0643,height=14.0321,x=21,y=323,xScale=0.438504*1,yScale=0.438504*1,assetName='B01_12',
		rotation=270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='39',objType='LDImage',class='',width=21.7238,height=10.8619,x=98,y=164,xScale=0.339434*1,yScale=0.339434*1,assetName='B01_10',
		rotation=322,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='40',objType='LDImage',class='',width=21.7238,height=10.8619,x=124,y=164,xScale=0.339434*1,yScale=0.339434*1,assetName='B01_10',
		rotation=36,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='41',objType='LDImage',class='',width=21.7238,height=10.8619,x=130,y=186,xScale=0.339434*1,yScale=0.339434*1,assetName='B01_10',
		rotation=109,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='42',objType='LDImage',class='',width=21.7238,height=10.8619,x=112,y=202,xScale=0.339434*1,yScale=0.339434*1,assetName='B01_10',
		rotation=172,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='43',objType='LDImage',class='',width=21.7238,height=10.8619,x=91,y=188,xScale=0.339434*1,yScale=0.339434*1,assetName='B01_10',
		rotation=-111,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=20.9293,height=10.4647,x=277,y=302,xScale=0.32702*1,yScale=0.32702*1,assetName='B01_1',
		rotation=9,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='45',objType='LDImage',class='',width=20.9293,height=10.4647,x=297,y=290,xScale=0.32702*1,yScale=0.32702*1,assetName='B01_1',
		rotation=293,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='46',objType='LDImage',class='',width=20.9293,height=10.4647,x=260,y=286,xScale=0.32702*1,yScale=0.32702*1,assetName='B01_1',
		rotation=73,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='47',objType='LDImage',class='',width=20.9293,height=10.4647,x=269,y=264,xScale=0.32702*1,yScale=0.32702*1,assetName='B01_1',
		rotation=150,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='48',objType='LDImage',class='',width=20.9293,height=10.4647,x=293,y=267,xScale=0.32702*1,yScale=0.32702*1,assetName='B01_1',
		rotation=-134,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='49',objType='LDImage',class='',width=32,height=16,x=215,y=154,xScale=0.5*1,yScale=0.5*1,assetName='B01_0',
		rotation=-33,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='50',objType='LDImage',class='',width=26.4876,height=16,x=246,y=150,xScale=0.413868*1,yScale=0.5*1,assetName='B01_0',
		rotation=-340,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='51',objType='LDImage',class='',width=32.9991,height=16,x=227,y=217,xScale=0.51561*1,yScale=0.5*1,assetName='B01_0',
		rotation=-344,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='52',objType='LDImage',class='',width=32,height=16,x=262,y=208,xScale=0.5*1,yScale=0.5*1,assetName='B01_0',
		rotation=-47,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='53',objType='LDImage',class='',width=32,height=16,x=191,y=183,xScale=0.5*1,yScale=0.5*1,assetName='B01_0',
		rotation=-205,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='54',objType='LDImage',class='',width=25.7019,height=16,x=274,y=158,xScale=0.401593*1,yScale=0.5*1,assetName='B01_0',
		rotation=-354,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='55',objType='LDImage',class='',width=23.0489,height=16,x=284,y=189,xScale=0.360138*1,yScale=0.5*1,assetName='B01_0',
		rotation=-24,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='56',objType='LDImage',class='',width=25.9561,height=16,x=299,y=171,xScale=0.405563*1,yScale=0.5*1,assetName='B01_0',
		rotation=-292,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

