-- Generated by Level Director X v1.1.0 on mer feb 12 21:10:05 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B04']={}
	assets.spriteSheetData['B04'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['saturnolike_0']={file ='saturnolike.jpg',name='saturnolike_0',class='',aX=0.5,aY=0.5,width=564,height=1002,frame=0,spriteSheetName='saturnolike',frameCount=1,
		 }
	assets['B11Speciale_4']={file ='B11Speciale.png',name='B11Speciale_4',class='',aX=0.5,aY=0.5,width=64,height=32,frame=5,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B11Speciale_6']={file ='B11Speciale.png',name='B11Speciale_6',class='',aX=0.5,aY=0.5,width=64,height=32,frame=7,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_4']={file ='B04.png',name='B04_4',class='',aX=0.5,aY=0.5,width=64,height=32,frame=5,spriteSheetName='B04',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_5']={file ='B04.png',name='B04_5',class='',aX=0.5,aY=0.5,width=64,height=32,frame=6,spriteSheetName='B04',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_6']={file ='B04.png',name='B04_6',class='',aX=0.5,aY=0.5,width=64,height=32,frame=7,spriteSheetName='B04',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_11']={file ='B04.png',name='B04_11',class='',aX=0.5,aY=0.5,width=64,height=32,frame=12,spriteSheetName='B04',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level30' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='saturnolike_0',objType='LDImage',class='',width=331,height=588.053,x=154,y=241,xScale=0.586879*1,yScale=0.586879*1,assetName='saturnolike_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=48,y=217,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_4',
		rotation=35,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=163,y=338,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-336,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='3',objType='LDImage',class='',width=28.0205,height=16,x=305,y=274,xScale=0.43782*1,yScale=0.5*1,assetName='B04_11',
		rotation=-312,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=18,y=246,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-320,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=44,y=268,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-324,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=298,y=366,xScale=0.5*1,yScale=0.5*1,assetName='B04_6',
		rotation=331,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=74,y=287,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-329,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=104,y=305,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='9',objType='LDImage',class='',width=32,height=16,x=133,y=322,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-331,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=195,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-338,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='11',objType='LDImage',class='',width=32,height=16,x=228,y=364,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-342,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='12',objType='LDImage',class='',width=32,height=16,x=262,y=371,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-351,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='13',objType='LDImage',class='',width=32,height=16,x=311,y=334,xScale=0.5*1,yScale=0.5*1,assetName='B04_6',
		rotation=269,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='14',objType='LDImage',class='',width=32,height=16,x=300,y=299,xScale=0.5*1,yScale=0.5*1,assetName='B04_6',
		rotation=238,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='15',objType='LDImage',class='',width=32,height=16,x=278,y=271,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-312,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=20,y=271,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=48,y=292,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-326,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='18',objType='LDImage',class='',width=32,height=16,x=77,y=311,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-329,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='19',objType='LDImage',class='',width=32,height=16,x=106,y=329,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-331,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=137,y=345,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-335,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=168,y=359,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-335,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='22',objType='LDImage',class='',width=32,height=16,x=200,y=372,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-339,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='23',objType='LDImage',class='',width=27.3191,height=16,x=283,y=251,xScale=0.426861*1,yScale=0.5*1,assetName='B04_11',
		rotation=-314,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='24',objType='LDImage',class='',width=32,height=16,x=233,y=384,xScale=0.5*1,yScale=0.5*1,assetName='B04_6',
		rotation=19,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='25',objType='LDImage',class='',width=32,height=16,x=268,y=394,xScale=0.5*1,yScale=0.5*1,assetName='B04_6',
		rotation=2,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='26',objType='LDImage',class='',width=32,height=16,x=303,y=387,xScale=0.5*1,yScale=0.5*1,assetName='B04_6',
		rotation=332,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='27',objType='LDImage',class='',width=32,height=16,x=87,y=378,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-22,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='28',objType='LDImage',class='',width=32,height=16,x=122,y=373,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-351,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='29',objType='LDImage',class='',width=32,height=16,x=151,y=393,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-303,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='30',objType='LDImage',class='',width=32,height=16,x=20,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='31',objType='LDImage',class='',width=32,height=16,x=20,y=197,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='32',objType='LDImage',class='',width=32,height=16,x=19,y=171,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='33',objType='LDImage',class='',width=32,height=16,x=18,y=145,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='34',objType='LDImage',class='',width=32,height=16,x=17,y=120,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='35',objType='LDImage',class='',width=32,height=16,x=16,y=93,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='36',objType='LDImage',class='',width=32,height=16,x=46,y=166,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='37',objType='LDImage',class='',width=32,height=16,x=47,y=192,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='38',objType='LDImage',class='',width=32,height=16,x=45,y=141,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-323,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='39',objType='LDImage',class='',width=32,height=16,x=48,y=243,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-325,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='40',objType='LDImage',class='',width=32,height=16,x=78,y=262,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-329,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='41',objType='LDImage',class='',width=32,height=16,x=73,y=185,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-326,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='42',objType='LDImage',class='',width=32,height=16,x=77,y=237,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-326,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='43',objType='LDImage',class='',width=32,height=16,x=75,y=211,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-326,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=32,height=16,x=109,y=281,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='45',objType='LDImage',class='',width=32,height=16,x=104,y=230,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-327,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='46',objType='LDImage',class='',width=32,height=16,x=107,y=256,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-327,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='47',objType='LDImage',class='',width=32,height=16,x=136,y=274,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='48',objType='LDImage',class='',width=32,height=16,x=140,y=300,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='49',objType='LDImage',class='',width=32,height=16,x=171,y=317,xScale=0.5*1,yScale=0.5*1,assetName='B04_4',
		rotation=-335,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='50',objType='LDImage',class='',width=32,height=16,x=168,y=292,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-333,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='51',objType='LDImage',class='',width=32,height=16,x=203,y=330,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-338,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='52',objType='LDImage',class='',width=32,height=16,x=201,y=306,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-338,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='53',objType='LDImage',class='',width=32,height=16,x=235,y=342,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		rotation=-339,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='54',objType='LDImage',class='',width=32,height=16,x=117,y=395,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_6',
		rotation=9,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

