-- Generated by Level Director X v1.1.0 on mar feb 11 19:07:49 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B12']={}
	assets.spriteSheetData['B12'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['moonSmile_0']={file ='moonSmile.jpg',name='moonSmile_0',class='',aX=0.5,aY=0.5,width=564,height=1003,frame=0,spriteSheetName='moonSmile',frameCount=1,
		 }
	assets['B11Speciale_12']={file ='B11Speciale.png',name='B11Speciale_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B12_12']={file ='B12.png',name='B12_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B12',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level25' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	level.tipo='g'
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='moonSmile_0',objType='LDImage',class='',width=324.441,height=576.975,x=158,y=294,xScale=0.57525*1,yScale=0.575249*1,assetName='moonSmile_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=106,y=392,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-332,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=61,y=355,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-301,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='3',objType='LDImage',class='',width=32,height=16,x=48,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=63,y=234,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-243,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=108,y=197,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-210,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=160,y=404,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=163,y=185,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=259,y=235,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-121,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='9',objType='LDImage',class='',width=32,height=16,x=215,y=392,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-28,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=257,y=354,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-61,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='11',objType='LDImage',class='',width=32,height=16,x=216,y=196,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-151,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='12',objType='LDImage',class='',width=32,height=16,x=273,y=295,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-91,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='13',objType='LDImage',class='',width=32,height=16,x=130,y=170,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=349,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='14',objType='LDImage',class='',width=32,height=16,x=72,y=198,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-221,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='15',objType='LDImage',class='',width=32,height=16,x=35,y=259,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-256,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=194,y=170,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-170,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=251,y=200,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-138,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='18',objType='LDImage',class='',width=32,height=16,x=34,y=330,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-281,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='19',objType='LDImage',class='',width=32,height=16,x=71,y=391,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-324,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=128,y=419,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-349,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=192,y=419,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-10,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='22',objType='LDImage',class='',width=32,height=16,x=286,y=260,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-102,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='23',objType='LDImage',class='',width=32,height=16,x=251,y=389,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-37,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='24',objType='LDImage',class='',width=32,height=16,x=286,y=330,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-76,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='25',objType='LDImage',class='',width=37.586,height=18.793,x=90,y=163,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=-208,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='26',objType='LDImage',class='',width=37.586,height=18.793,x=34,y=215,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=-239,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='27',objType='LDImage',class='',width=37.586,height=18.793,x=14,y=293,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=-269,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='28',objType='LDImage',class='',width=37.586,height=18.793,x=32,y=372,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=-301,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='29',objType='LDImage',class='',width=37.586,height=18.793,x=88,y=424,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=-332,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='30',objType='LDImage',class='',width=37.586,height=18.793,x=159,y=440,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='31',objType='LDImage',class='',width=37.586,height=18.793,x=231,y=424,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=331,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='32',objType='LDImage',class='',width=37.586,height=18.793,x=287,y=371,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=301,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='33',objType='LDImage',class='',width=37.586,height=18.793,x=307,y=295,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=271,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='34',objType='LDImage',class='',width=37.586,height=18.793,x=289,y=217,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=238,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='36',objType='LDImage',class='',width=37.586,height=18.793,x=233,y=165,xScale=0.587281*1,yScale=0.587281*1,assetName='B12_12',
		rotation=-152,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='37',objType='LDImage',class='',width=32,height=16,x=187,y=281,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_12',
		rotation=-15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='38',objType='LDImage',class='',width=32,height=16,x=221,y=272,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_12',
		rotation=-15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='39',objType='LDImage',class='',width=27.8259,height=13.913,x=66,y=321,xScale=0.43478*1,yScale=0.43478*1,assetName='B12_12',
		rotation=-281,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='40',objType='LDImage',class='',width=27.8259,height=13.913,x=92,y=224,xScale=0.43478*1,yScale=0.43478*1,assetName='B12_12',
		rotation=-215,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='41',objType='LDImage',class='',width=27.8259,height=13.913,x=66,y=268,xScale=0.43478*1,yScale=0.43478*1,assetName='B12_12',
		rotation=-253,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='42',objType='LDImage',class='',width=27.8259,height=13.913,x=90,y=362,xScale=0.43478*1,yScale=0.43478*1,assetName='B12_12',
		rotation=-325,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='43',objType='LDImage',class='',width=27.8259,height=13.913,x=135,y=384,xScale=0.43478*1,yScale=0.434781*1,assetName='B12_12',
		rotation=-350,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='44',objType='LDImage',class='',width=27.8259,height=13.913,x=183,y=385,xScale=0.43478*1,yScale=0.434781*1,assetName='B12_12',
		rotation=-13,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='45',objType='LDImage',class='',width=27.8259,height=13.913,x=227,y=362,xScale=0.43478*1,yScale=0.434781*1,assetName='B12_12',
		rotation=-36,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='46',objType='LDImage',class='',width=27.8259,height=13.913,x=252,y=320,xScale=0.43478*1,yScale=0.434781*1,assetName='B12_12',
		rotation=-77,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='47',objType='LDImage',class='',width=27.8259,height=13.913,x=138,y=203,xScale=0.43478*1,yScale=0.434781*1,assetName='B12_12',
		rotation=-191,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='48',objType='LDImage',class='',width=27.8259,height=13.913,x=186,y=202,xScale=0.43478*1,yScale=0.434781*1,assetName='B12_12',
		rotation=-169,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='49',objType='LDImage',class='',width=27.8259,height=13.913,x=253,y=267,xScale=0.43478*1,yScale=0.434781*1,assetName='B12_12',
		rotation=-101,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='35',objType='LDImage',class='',width=27.8259,height=13.913,x=229,y=225,xScale=0.43478*1,yScale=0.434781*1,assetName='B12_12',
		rotation=-138,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

