-- Generated by Level Director X v1.1.0 on mar feb 11 12:07:25 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B05']={}
	assets.spriteSheetData['B05'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B05_40']={}
	assets.spriteSheetData['B05_40'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['natura4_0']={file ='natura4.jpg',name='natura4_0',class='',aX=0.5,aY=0.5,width=563,height=847,frame=0,spriteSheetName='natura4',frameCount=1,
		 }
	assets['B05_8']={file ='B05.png',name='B05_8',class='',aX=0.5,aY=0.5,width=64,height=32,frame=9,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_11']={file ='B05.png',name='B05_11',class='',aX=0.5,aY=0.5,width=64,height=32,frame=12,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_14']={file ='B05.png',name='B05_14',class='',aX=0.5,aY=0.5,width=64,height=32,frame=15,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_15']={file ='B05.png',name='B05_15',class='',aX=0.5,aY=0.5,width=64,height=32,frame=16,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_20']={file ='B05.png',name='B05_20',class='',aX=0.5,aY=0.5,width=64,height=32,frame=21,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_24']={file ='B05.png',name='B05_24',class='',aX=0.5,aY=0.5,width=64,height=32,frame=25,spriteSheetName='B05',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Rectangle',shape={},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_14']={file ='B04.png',name='B04_14',class='',aX=0.5,aY=0.5,width=64,height=32,frame=15,spriteSheetName='B05_40',frameCount=25,
		 }
	assets['B11Speciale_7']={file ='B11Speciale.png',name='B11Speciale_7',class='',aX=0.5,aY=0.5,width=64,height=32,frame=8,spriteSheetName='B11Speciale',frameCount=25,
		 }
	assets['B11Speciale_16']={file ='B11Speciale.png',name='B11Speciale_16',class='',aX=0.5,aY=0.5,width=64,height=32,frame=17,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level04' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='natura4_0',objType='LDImage',class='',width=320,height=480,x=160,y=240,xScale=0.568384*1,yScale=0.566706*1,assetName='natura4_0',
		userProps = {},
		},
	{name='B05_1',objType='LDImage',class='',width=32,height=16,x=9,y=141,xScale=0.5*1,yScale=0.5*1,assetName='B05_8',
		rotation=-14,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_14',objType='LDImage',class='',width=32,height=16,x=17,y=163,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=-353,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_3',objType='LDImage',class='',width=32,height=16,x=46,y=168,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=-348,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_4',objType='LDImage',class='',width=32,height=16,x=75,y=174,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=-349,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_5',objType='LDImage',class='',width=32,height=16,x=106,y=179,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=-352,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_6',objType='LDImage',class='',width=32,height=16,x=136,y=181,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		userProps = {},
		},
	{name='B05_24',objType='LDImage',class='',width=64,height=32,x=203,y=255,xScale=1*1,yScale=1*1,assetName='B05_24',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='B05_12',objType='LDImage',class='',width=32,height=16,x=36,y=135,xScale=0.5*1,yScale=0.5*1,assetName='B05_8',
		rotation=-12,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_13',objType='LDImage',class='',width=32,height=16,x=65,y=130,xScale=0.5*1,yScale=0.5*1,assetName='B05_8',
		rotation=-6,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_17',objType='LDImage',class='',width=32,height=16,x=64,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_18',objType='LDImage',class='',width=32,height=16,x=80,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_19',objType='LDImage',class='',width=32,height=16,x=32,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_20',objType='LDImage',class='',width=32,height=16,x=96,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_21',objType='LDImage',class='',width=32,height=16,x=16,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_25',objType='LDImage',class='',width=32,height=16,x=112,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_26',objType='LDImage',class='',width=32,height=16,x=32,y=248,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_28',objType='LDImage',class='',width=32,height=16,x=96,y=248,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_29',objType='LDImage',class='',width=32,height=16,x=48,y=232,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_30',objType='LDImage',class='',width=32,height=16,x=80,y=232,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_31',objType='LDImage',class='',width=32,height=16,x=64,y=216,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_32',objType='LDImage',class='',width=32,height=16,x=64,y=248,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_33',objType='LDImage',class='',width=32,height=16,x=48,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_34',objType='LDImage',class='',width=32,height=16,x=80,y=264,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_35',objType='LDImage',class='',width=32,height=16,x=48,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_36',objType='LDImage',class='',width=32,height=16,x=112,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_37',objType='LDImage',class='',width=32,height=16,x=16,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B05_11',
		userProps = {},
		},
	{name='B05_38',objType='LDImage',class='',width=32,height=16,x=283,y=204,xScale=0.5*1,yScale=0.5*1,assetName='B05_15',
		userProps = {},
		},
	{name='B05_27',objType='LDImage',class='',width=32,height=16,x=267,y=220,xScale=0.5*1,yScale=0.5*1,assetName='B05_15',
		userProps = {},
		},
	{name='B05_8',objType='LDImage',class='',width=32,height=16,x=299,y=220,xScale=0.5*1,yScale=0.5*1,assetName='B05_15',
		userProps = {},
		},
	{name='B05_23',objType='LDImage',class='',width=32,height=16,x=283,y=236,xScale=0.5*1,yScale=0.5*1,assetName='B05_15',
		userProps = {},
		},
	{name='B05_22',objType='LDImage',class='',width=32,height=16,x=278,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_16',
		rotation=-25,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='B05_11',objType='LDImage',class='',width=32,height=16,x=276,y=92,xScale=0.5*1,yScale=0.5*1,assetName='B05_8',
		rotation=-8,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_2',objType='LDImage',class='',width=32,height=16,x=304,y=90,xScale=0.5*1,yScale=0.5*1,assetName='B05_8',
		userProps = {},
		},
	{name='B05_39',objType='LDImage',class='',width=32,height=16,x=165,y=179,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=-9,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_7',objType='LDImage',class='',width=32,height=16,x=193,y=173,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=345,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_15',objType='LDImage',class='',width=32,height=16,x=222,y=166,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=-11,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_9',objType='LDImage',class='',width=32,height=16,x=251,y=161,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=352,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B05_10',objType='LDImage',class='',width=32,height=16,x=279,y=159,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		userProps = {},
		},
	{name='B05_16',objType='LDImage',class='',width=32,height=16,x=310,y=159,xScale=0.5*1,yScale=0.5*1,assetName='B05_14',
		rotation=-1,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

