-- Generated by Level Director X v1.1.0 on lun feb 3 16:18:25 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B04']={}
	assets.spriteSheetData['B04'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['dino_0']={file ='dino.jpg',name='dino_0',class='',aX=0.5,aY=0.5,width=1110,height=785,frame=0,spriteSheetName='dino',frameCount=1,
		 }
	assets['B11Speciale_11']={file ='B11Speciale.png',name='B11Speciale_11',class='',aX=0.5,aY=0.5,width=64,height=32,frame=12,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_5']={file ='B04.png',name='B04_5',class='',aX=0.5,aY=0.5,width=64,height=32,frame=6,spriteSheetName='B04',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_11']={file ='B04.png',name='B04_11',class='',aX=0.5,aY=0.5,width=64,height=32,frame=12,spriteSheetName='B04',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_20']={file ='B04.png',name='B04_20',class='',aX=0.5,aY=0.5,width=64,height=32,frame=21,spriteSheetName='B04',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B04_23']={file ='B04.png',name='B04_23',class='',aX=0.5,aY=0.5,width=64,height=32,frame=24,spriteSheetName='B04',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-33,-17,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level15' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='sfondo',objType='LDImage',class='',width=678.115,height=479.568,x=147,y=244,xScale=0.610914*1,yScale=0.610915*1,assetName='dino_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=27,y=180,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=17,y=155,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		userProps = {},
		},
	{name='3',objType='LDImage',class='',width=32,height=16,x=27,y=130,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=52,y=191,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=52,y=120,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=77,y=180,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=87,y=155,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=77,y=130,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=135,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='9',objType='LDImage',class='',width=32,height=16,x=52,y=155,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_11',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=296,y=277,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='11',objType='LDImage',class='',width=32,height=16,x=271,y=288,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='12',objType='LDImage',class='',width=32,height=16,x=246,y=227,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='13',objType='LDImage',class='',width=32,height=16,x=306,y=252,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='14',objType='LDImage',class='',width=32,height=16,x=236,y=252,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		userProps = {},
		},
	{name='15',objType='LDImage',class='',width=32,height=16,x=296,y=227,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=135,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=246,y=277,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=271,y=217,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='18',objType='LDImage',class='',width=32,height=16,x=77,y=373,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='19',objType='LDImage',class='',width=32,height=16,x=52,y=384,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=27,y=323,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=87,y=348,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='22',objType='LDImage',class='',width=32,height=16,x=17,y=348,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		userProps = {},
		},
	{name='23',objType='LDImage',class='',width=32,height=16,x=77,y=323,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=135,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='24',objType='LDImage',class='',width=32,height=16,x=52,y=348,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_11',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='25',objType='LDImage',class='',width=32,height=16,x=27,y=373,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='26',objType='LDImage',class='',width=32,height=16,x=52,y=313,xScale=0.5*1,yScale=0.5*1,assetName='B04_23',
		rotation=90,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='27',objType='LDImage',class='',width=32,height=16,x=271,y=252,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='28',objType='LDImage',class='',width=32,height=16,x=199,y=188,xScale=0.5*1,yScale=0.5*1,assetName='B04_20',
		rotation=-45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='29',objType='LDImage',class='',width=32,height=16,x=221,y=165,xScale=0.5*1,yScale=0.5*1,assetName='B04_20',
		rotation=-45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='30',objType='LDImage',class='',width=32,height=16,x=176,y=211,xScale=0.5*1,yScale=0.5*1,assetName='B04_20',
		rotation=-45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='31',objType='LDImage',class='',width=32,height=16,x=175,y=292,xScale=0.5*1,yScale=0.5*1,assetName='B04_20',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='32',objType='LDImage',class='',width=32,height=16,x=198,y=315,xScale=0.5*1,yScale=0.5*1,assetName='B04_20',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='33',objType='LDImage',class='',width=32,height=16,x=221,y=337,xScale=0.5*1,yScale=0.5*1,assetName='B04_20',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='34',objType='LDImage',class='',width=32,height=16,x=255,y=151,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='35',objType='LDImage',class='',width=32,height=16,x=304,y=151,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='36',objType='LDImage',class='',width=32,height=16,x=279,y=135,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='37',objType='LDImage',class='',width=32,height=16,x=304,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='38',objType='LDImage',class='',width=32,height=16,x=280,y=368,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='39',objType='LDImage',class='',width=32,height=16,x=255,y=352,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='40',objType='LDImage',class='',width=32,height=16,x=151,y=235,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='41',objType='LDImage',class='',width=32,height=16,x=151,y=251,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='42',objType='LDImage',class='',width=32,height=16,x=151,y=267,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='43',objType='LDImage',class='',width=32,height=16,x=119,y=235,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=32,height=16,x=119,y=251,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		userProps = {},
		},
	{name='45',objType='LDImage',class='',width=32,height=16,x=119,y=267,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		userProps = {},
		},
	{name='46',objType='LDImage',class='',width=32,height=16,x=87,y=267,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='47',objType='LDImage',class='',width=32,height=16,x=87,y=251,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='48',objType='LDImage',class='',width=32,height=16,x=87,y=235,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='49',objType='LDImage',class='',width=32,height=16,x=23,y=267,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='50',objType='LDImage',class='',width=32,height=16,x=23,y=251,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='51',objType='LDImage',class='',width=32,height=16,x=55,y=235,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		userProps = {},
		},
	{name='52',objType='LDImage',class='',width=32,height=16,x=55,y=251,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		userProps = {},
		},
	{name='53',objType='LDImage',class='',width=32,height=16,x=23,y=235,xScale=0.5*1,yScale=0.5*1,assetName='B04_11',
		userProps = {},
		},
	{name='54',objType='LDImage',class='',width=32,height=16,x=55,y=267,xScale=0.5*1,yScale=0.5*1,assetName='B04_5',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

