-- Generated by Level Director X v1.1.0 on sab feb 1 22:08:23 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B09']={}
	assets.spriteSheetData['B09'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['c7964f1e4a3aae3ef877dfabded42405_0']={file ='c7964f1e4a3aae3ef877dfabded42405.jpg',name='c7964f1e4a3aae3ef877dfabded42405_0',class='',aX=0.5,aY=0.5,width=564,height=752,frame=0,spriteSheetName='c7964f1e4a3aae3ef877dfabded42405',frameCount=1,
		 }
	assets['cieloegypt.png_0']={file ='cieloegypt.png.jpg',name='cieloegypt.png_0',class='',aX=0.5,aY=0.5,width=563,height=98,frame=0,spriteSheetName='cieloegypt.png',frameCount=1,
		 }
	assets['B11Speciale_19']={file ='B11Speciale.png',name='B11Speciale_19',class='',aX=0.5,aY=0.5,width=64,height=32,frame=20,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_2']={file ='B09.png',name='B09_2',class='',aX=0.5,aY=0.5,width=64,height=32,frame=3,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B09_19']={file ='B09.png',name='B09_19',class='',aX=0.5,aY=0.5,width=64,height=32,frame=20,spriteSheetName='B09',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level11' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='cieloegypt.png_0',objType='LDImage',class='',width=320,height=49,x=160,y=15,xScale=0.568384*1,yScale=0.5*1,assetName='cieloegypt.png_0',
		userProps = {},
		},
	{name='sfondo',objType='LDImage',class='',width=450,height=807.326,x=225,y=422,xScale=0.797872*1,yScale=1.07357*1,assetName='c7964f1e4a3aae3ef877dfabded42405_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=61,y=292,xScale=0.5*1,yScale=0.5*1,assetName='B09_19',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=96,y=296,xScale=0.5*1,yScale=0.5*1,assetName='B09_19',
		rotation=5,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='3',objType='LDImage',class='',width=32,height=16,x=131,y=299,xScale=0.5*1,yScale=0.5*1,assetName='B09_19',
		rotation=1,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=168,y=299,xScale=0.5*1,yScale=0.5*1,assetName='B09_19',
		rotation=356,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=72,y=261,xScale=0.5*1,yScale=0.5*1,assetName='B09_19',
		rotation=289,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=160,y=266,xScale=0.5*1,yScale=0.5*1,assetName='B09_19',
		rotation=248,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='7',objType='LDImage',class='',width=57.9301,height=16,x=114,y=248,xScale=0.905158*1,yScale=0.5*1,assetName='B09_19',
		rotation=1,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=114,y=270,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_19',
		rotation=-357,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='9',objType='LDImage',class='',width=57.9301,height=16,x=113,y=230,xScale=0.905158*1,yScale=0.5*1,assetName='B09_19',
		rotation=1,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='10',objType='LDImage',class='',width=48.2104,height=16,x=266,y=297,xScale=0.753287*1,yScale=0.5*1,assetName='B09_19',
		rotation=-347,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='11',objType='LDImage',class='',width=24,height=16,x=284,y=269,xScale=0.375*1,yScale=0.5*1,assetName='B09_19',
		rotation=-347,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='12',objType='LDImage',class='',width=34.8029,height=16,x=274,y=283,xScale=0.543795*1,yScale=0.5*1,assetName='B09_19',
		rotation=-347,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='4' },},
		},
	{name='13',objType='LDImage',class='',width=30.4846,height=15.2423,x=16,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='14',objType='LDImage',class='',width=30.4846,height=15.2423,x=47,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='15',objType='LDImage',class='',width=30.4846,height=15.2423,x=79,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='16',objType='LDImage',class='',width=30.4846,height=15.2423,x=111,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='17',objType='LDImage',class='',width=30.4846,height=15.2423,x=143,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='18',objType='LDImage',class='',width=30.4846,height=15.2423,x=174,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='19',objType='LDImage',class='',width=30.4846,height=15.2423,x=206,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='20',objType='LDImage',class='',width=30.4846,height=15.2423,x=237,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='21',objType='LDImage',class='',width=30.4846,height=15.2423,x=269,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='22',objType='LDImage',class='',width=30.4846,height=15.2423,x=301,y=404,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='23',objType='LDImage',class='',width=30.4846,height=15.2423,x=237,y=387,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='24',objType='LDImage',class='',width=30.4846,height=15.2423,x=110,y=387,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='25',objType='LDImage',class='',width=30.4846,height=15.2423,x=142,y=387,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='26',objType='LDImage',class='',width=30.4846,height=15.2423,x=174,y=387,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='27',objType='LDImage',class='',width=30.4846,height=15.2423,x=205,y=387,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='28',objType='LDImage',class='',width=30.4846,height=15.2423,x=78,y=387,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='29',objType='LDImage',class='',width=30.4846,height=15.2423,x=174,y=370,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='30',objType='LDImage',class='',width=30.4846,height=15.2423,x=206,y=370,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='31',objType='LDImage',class='',width=30.4846,height=15.2423,x=142,y=370,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='32',objType='LDImage',class='',width=30.4846,height=15.2423,x=110,y=370,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='33',objType='LDImage',class='',width=30.4846,height=15.2423,x=142,y=353,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='34',objType='LDImage',class='',width=30.4846,height=15.2423,x=174,y=353,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='35',objType='LDImage',class='',width=30.4846,height=15.2423,x=157,y=336,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		userProps = {},
		},
	{name='36',objType='LDImage',class='',width=30.4846,height=15.2423,x=82,y=320,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='37',objType='LDImage',class='',width=30.4846,height=15.2423,x=19,y=320,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='38',objType='LDImage',class='',width=30.4846,height=15.2423,x=68,y=354,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='39',objType='LDImage',class='',width=30.4846,height=15.2423,x=82,y=337,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='40',objType='LDImage',class='',width=30.4846,height=15.2423,x=115,y=320,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='41',objType='LDImage',class='',width=30.4846,height=15.2423,x=51,y=337,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='42',objType='LDImage',class='',width=30.4846,height=15.2423,x=51,y=320,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='43',objType='LDImage',class='',width=30.4846,height=15.2423,x=266,y=337,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=30.4846,height=15.2423,x=298,y=320,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='45',objType='LDImage',class='',width=30.4846,height=15.2423,x=234,y=337,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='46',objType='LDImage',class='',width=30.4846,height=15.2423,x=266,y=320,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='47',objType='LDImage',class='',width=30.4846,height=15.2423,x=251,y=354,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='48',objType='LDImage',class='',width=30.4846,height=15.2423,x=202,y=320,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='49',objType='LDImage',class='',width=30.4846,height=15.2423,x=234,y=320,xScale=0.476322*1,yScale=0.476322*1,assetName='B09_2',
		rotation=-180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

