-- Generated by Level Director X v1.1.0 on ven ott 25 20:14:04 2019 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets['finestra_pausa_0']={file ='finestra_pausa.png',name='finestra_pausa_0',class='',aX=0.5,aY=0.5,width=640,height=960,frame=0,spriteSheetName='finestra_pausa',frameCount=1,
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='schermat_pausa_level' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- pulsanti ------------------------------------------------------------------------------------
	level.layers['pulsanti']={} 
	level.layers['pulsanti'].view=display.newGroup() 
	level.layers['pulsanti'].name='pulsanti' 
	if (level.parallaxEnabled) then
		level.layers['pulsanti'].speed={x=0,y=0}
		level.layers['pulsanti'].repeated=false
		level.layers['pulsanti'].cullingMethod=0
	else
		level.layers['pulsanti'].cullingMethod=0 
	end
	level.layers['pulsanti'].objects={} 
	objects = {
	{name='finestra_pausa_0',objType='LDImage',class='',width=320,height=480,x=160,y=240,xScale=0.5*1,yScale=0.5*1,assetName='finestra_pausa_0',
		userProps = {},
		},
	{name='volumeeffetti+',objType='LDButton',class='',width=33.5,height=32.25,x=150,y=152,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='text',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.75,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255}},
		userProps = {},
		},
	{name='volumeeffetti-',objType='LDButton',class='',width=33.5,height=32.25,x=244,y=152,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='text',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.75,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255}},
		userProps = {},
		},
	{name='volumemusica+',objType='LDButton',class='',width=33.5,height=32.25,x=151,y=218,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='text',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.75,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255}},
		userProps = {},
		},
	{name='volumemusica-',objType='LDButton',class='',width=33.5,height=32.25,x=245,y=219,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='text',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.75,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255}},
		userProps = {},
		},
	{name='backtomenu',objType='LDButton',class='',width=219.5,height=32.75,x=156,y=283,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='text',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=109.75,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255}},
		userProps = {},
		},
	{name='ok',objType='LDButton',class='',width=104,height=67.6425,x=156,y=383,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='text',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=52,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=255/255}},
		userProps = {},
		},
	{name='rect_8',objType='LDRectangle',class='',width=32,height=32,x=199,y=151,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=16,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		userProps = {},
		},
	{name='rect_9',objType='LDRectangle',class='',width=32,height=32,x=199,y=218,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=16,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['pulsanti'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['pulsanti'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

