-- Generated by Level Director X v1.1.0 on lun feb 17 19:00:16 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B03']={}
	assets.spriteSheetData['B03'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['dadlpfl-d0157e66-8eda-44aa-9de7-da9968416cf3_0']={file ='dadlpfl-d0157e66-8eda-44aa-9de7-da9968416cf3.jpg',name='dadlpfl-d0157e66-8eda-44aa-9de7-da9968416cf3_0',class='',aX=0.5,aY=0.5,width=566,height=800,frame=0,spriteSheetName='dadlpfl-d0157e66-8eda-44aa-9de7-da9968416cf3',frameCount=1,
		 }
	assets['B11Speciale_6']={file ='B11Speciale.png',name='B11Speciale_6',class='',aX=0.5,aY=0.5,width=64,height=32,frame=7,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_2']={file ='B03.png',name='B03_2',class='',aX=0.5,aY=0.5,width=64,height=32,frame=3,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_3']={file ='B03.png',name='B03_3',class='',aX=0.5,aY=0.5,width=64,height=32,frame=4,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_15']={file ='B03.png',name='B03_15',class='',aX=0.5,aY=0.5,width=64,height=32,frame=16,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_16']={file ='B03.png',name='B03_16',class='',aX=0.5,aY=0.5,width=64,height=32,frame=17,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level06' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='dadlpfl-d0157e66-8eda-44aa-9de7-da9968416cf3_0',objType='LDImage',class='',width=320,height=507.667,x=160,y=299,xScale=0.565371*1,yScale=0.634584*1,assetName='dadlpfl-d0157e66-8eda-44aa-9de7-da9968416cf3_0',
		userProps = {},
		},
	{name='3',objType='LDImage',class='',width=24.4073,height=16,x=194,y=369,xScale=0.381364*1,yScale=0.5*1,assetName='B03_3',
		rotation=-274,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=166,y=395,xScale=0.5*1,yScale=0.5*1,assetName='B03_15',
		rotation=-358,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=131,y=387,xScale=0.5*1,yScale=0.5*1,assetName='B03_15',
		rotation=-338,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=101,y=365,xScale=0.5*1,yScale=0.5*1,assetName='B03_15',
		rotation=-310,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=85,y=334,xScale=0.5*1,yScale=0.5*1,assetName='B03_15',
		rotation=-289,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='8',objType='LDImage',class='',width=49.1183,height=16,x=82,y=236,xScale=0.767473*1,yScale=0.5*1,assetName='B03_15',
		rotation=-262,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='9',objType='LDImage',class='',width=48.7548,height=16,x=85,y=167,xScale=0.761794*1,yScale=0.5*1,assetName='B03_15',
		rotation=-279,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=201,y=391,xScale=0.5*1,yScale=0.5*1,assetName='B03_16',
		rotation=345,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='11',objType='LDImage',class='',width=27.9168,height=16,x=230,y=373,xScale=0.4362*1,yScale=0.5*1,assetName='B03_16',
		rotation=312,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='12',objType='LDImage',class='',width=22.7142,height=16,x=246,y=349,xScale=0.354909*1,yScale=0.5*1,assetName='B03_16',
		rotation=295,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='13',objType='LDImage',class='',width=32,height=16,x=251,y=274,xScale=0.5*1,yScale=0.5*1,assetName='B03_16',
		rotation=253,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='14',objType='LDImage',class='',width=47.1533,height=16,x=232,y=236,xScale=0.73677*1,yScale=0.5*1,assetName='B03_16',
		rotation=238,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='15',objType='LDImage',class='',width=28.3885,height=16,x=172,y=173,xScale=0.44357*1,yScale=0.5*1,assetName='B03_16',
		rotation=215,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=144,y=158,xScale=0.5*1,yScale=0.5*1,assetName='B03_16',
		rotation=199,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=110,y=149,xScale=0.5*1,yScale=0.5*1,assetName='B03_16',
		rotation=184,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='18',objType='LDImage',class='',width=28.9657,height=16,x=188,y=313,xScale=0.452589*1,yScale=0.5*1,assetName='B03_3',
		rotation=83,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='19',objType='LDImage',class='',width=26.6935,height=16,x=182,y=280,xScale=0.417086*1,yScale=0.5*1,assetName='B03_3',
		rotation=77,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=144,y=200,xScale=0.5*1,yScale=0.5*1,assetName='B03_3',
		rotation=53,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=119,y=174,xScale=0.5*1,yScale=0.5*1,assetName='B03_3',
		rotation=47,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='22',objType='LDImage',class='',width=26,height=16,x=270,y=160,xScale=0.40625*1,yScale=0.5*1,assetName='B11Speciale_6',
		rotation=-14,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='23',objType='LDImage',class='',width=32,height=16,x=209,y=167,xScale=0.5*1,yScale=0.5*1,assetName='B03_2',
		rotation=-43,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='24',objType='LDImage',class='',width=32,height=16,x=238,y=146,xScale=0.5*1,yScale=0.5*1,assetName='B03_2',
		rotation=-25,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='25',objType='LDImage',class='',width=32,height=16,x=273,y=139,xScale=0.5*1,yScale=0.5*1,assetName='B03_2',
		rotation=-6,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='26',objType='LDImage',class='',width=50.4513,height=16,x=299,y=158,xScale=0.788302*1,yScale=0.5*1,assetName='B03_2',
		rotation=89,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='27',objType='LDImage',class='',width=32,height=16,x=242,y=196,xScale=0.5*1,yScale=0.5*1,assetName='B03_2',
		rotation=-27,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='28',objType='LDImage',class='',width=32,height=16,x=273,y=181,xScale=0.5*1,yScale=0.5*1,assetName='B03_2',
		rotation=-17,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='29',objType='LDImage',class='',width=32,height=16,x=53,y=319,xScale=0.5*1,yScale=0.5*1,assetName='B03_2',
		rotation=-6,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='30',objType='LDImage',class='',width=26.5311,height=16,x=22,y=319,xScale=0.414548*1,yScale=0.5*1,assetName='B03_2',
		rotation=-355,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='31',objType='LDImage',class='',width=32,height=16,x=13,y=292,xScale=0.5*1,yScale=0.5*1,assetName='B03_2',
		rotation=-265,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='32',objType='LDImage',class='',width=46.7432,height=16,x=45,y=274,xScale=0.730363*1,yScale=0.5*1,assetName='B03_2',
		rotation=-7,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='33',objType='LDImage',class='',width=38.6563,height=16,x=57,y=207,xScale=0.604005*1,yScale=0.5*1,assetName='B03_2',
		rotation=-4,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='34',objType='LDImage',class='',width=26.0448,height=16,x=29,y=200,xScale=0.40695*1,yScale=0.5*1,assetName='B03_2',
		rotation=-243,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='35',objType='LDImage',class='',width=29.7771,height=16,x=30,y=171,xScale=0.465267*1,yScale=0.5*1,assetName='B03_2',
		rotation=-137,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='36',objType='LDImage',class='',width=31.3321,height=16,x=54,y=158,xScale=0.489564*1,yScale=0.5*1,assetName='B03_2',
		rotation=-4,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='37',objType='LDImage',class='',width=35.3971,height=16,x=284,y=301,xScale=0.55308*1,yScale=0.5*1,assetName='B03_2',
		rotation=-24,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='38',objType='LDImage',class='',width=23.8504,height=16,x=270,y=256,xScale=0.372663*1,yScale=0.5*1,assetName='B03_2',
		rotation=-26,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='1',objType='LDImage',class='',width=28.132,height=16,x=293,y=252,xScale=0.439563*1,yScale=0.5*1,assetName='B03_2',
		rotation=-275,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='2',objType='LDImage',class='',width=22.7707,height=16,x=301,y=278,xScale=0.355792*1,yScale=0.5*1,assetName='B03_2',
		rotation=9,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='dadlpfl-d0157e66-8eda-44aa-9de7-da9968416cf3_42',objType='LDImage',class='',width=320,height=524,x=160,y=-215,xScale=0.565371*1,yScale=0.655*1,assetName='dadlpfl-d0157e66-8eda-44aa-9de7-da9968416cf3_0',
		rotation=180,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

