-- Generated by Level Director X v1.1.0 on ven ott 25 17:32:49 2019 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets['finestra_opzioni_0']={file ='finestra_opzioni.png',name='finestra_opzioni_0',class='',aX=0.5,aY=0.5,width=640,height=960,frame=0,spriteSheetName='finestra_opzioni',frameCount=1,
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='opzioni' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='finestra_opzioni_0',objType='LDImage',class='',width=318.667,height=478,x=161,y=251,xScale=0.497917*1,yScale=0.497917*1,assetName='finestra_opzioni_0',
		userProps = {},
		},
	{name='rect_2',objType='LDRectangle',class='',width=42.5,height=39,x=202,y=162,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=21.25,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		userProps = {},
		},
	{name='rect_3',objType='LDRectangle',class='',width=42.5,height=39,x=203,y=230,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=21.25,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	---- bottoni ------------------------------------------------------------------------------------
	level.layers['bottoni']={} 
	level.layers['bottoni'].view=display.newGroup() 
	level.layers['bottoni'].name='bottoni' 
	if (level.parallaxEnabled) then
		level.layers['bottoni'].speed={x=0,y=0}
		level.layers['bottoni'].repeated=false
		level.layers['bottoni'].cullingMethod=0
	else
		level.layers['bottoni'].cullingMethod=0 
	end
	level.layers['bottoni'].objects={} 
	objects = {
	{name='button_1',objType='LDButton',class='',width=33,height=32,x=152,y=163,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=0/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255}},
		userProps = {},
		},
	{name='button_2',objType='LDButton',class='',width=33,height=32,x=246,y=163,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='text',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=0/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255}},
		userProps = {},
		},
	{name='button_3',objType='LDButton',class='',width=33,height=32,x=153,y=229,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=0/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255}},
		userProps = {},
		},
	{name='button_4',objType='LDButton',class='',width=33,height=32,x=247,y=228,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='text',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=0/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255}},
		userProps = {},
		},
	{name='button_5',objType='LDButton',class='',width=83,height=53.5,x=158,y=397,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=41.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=0/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255}},
		userProps = {},
		},
	{name='button_6',objType='LDButton',class='',width=142.5,height=41.5,x=159,y=291,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=71.25,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=1/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=0/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255}},
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['bottoni'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['bottoni'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

