-- Generated by Level Director X v1.1.0 on mar feb 11 20:37:20 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B12']={}
	assets.spriteSheetData['B12'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['astronautHelmet_0']={file ='astronautHelmet.jpg',name='astronautHelmet_0',class='',aX=0.5,aY=0.5,width=564,height=1002,frame=0,spriteSheetName='astronautHelmet',frameCount=1,
		 }
	assets['B11Speciale_11']={file ='B11Speciale.png',name='B11Speciale_11',class='',aX=0.5,aY=0.5,width=64,height=32,frame=12,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B12_12']={file ='B12.png',name='B12_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B12',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B12_23']={file ='B12.png',name='B12_23',class='',aX=0.5,aY=0.5,width=64,height=32,frame=24,spriteSheetName='B12',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level27' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='astronautHelmet_0',objType='LDImage',class='',width=321.649,height=510,x=160,y=252,xScale=0.5703*1,yScale=0.508982*1,assetName='astronautHelmet_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=77,y=376,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=14,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=49,y=355,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=52,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='3',objType='LDImage',class='',width=32,height=16,x=32,y=324,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=72,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=28,y=291,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=91,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=112,y=375,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=343,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=145,y=369,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=359,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=177,y=368,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		userProps = {},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=212,y=375,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=18,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='9',objType='LDImage',class='',width=32,height=16,x=248,y=374,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=340,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=30,y=257,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=100,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='11',objType='LDImage',class='',width=32,height=16,x=41,y=224,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=115,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='12',objType='LDImage',class='',width=32,height=16,x=63,y=195,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=140,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='13',objType='LDImage',class='',width=32,height=16,x=93,y=178,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=163,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='14',objType='LDImage',class='',width=32,height=16,x=127,y=172,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=175,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='15',objType='LDImage',class='',width=32,height=16,x=161,y=170,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=-179,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=194,y=172,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=-173,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=227,y=178,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=-166,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='18',objType='LDImage',class='',width=32,height=16,x=258,y=193,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=-142,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='19',objType='LDImage',class='',width=32,height=16,x=280,y=221,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=-112,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=275,y=353,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=304,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=290,y=322,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=286,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='22',objType='LDImage',class='',width=32,height=16,x=294,y=288,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=268,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='23',objType='LDImage',class='',width=32,height=16,x=290,y=254,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=257,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='24',objType='LDImage',class='',width=32,height=16,x=22,y=389,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-308,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='25',objType='LDImage',class='',width=32,height=16,x=50,y=408,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-338,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='26',objType='LDImage',class='',width=32,height=16,x=82,y=419,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-346,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='27',objType='LDImage',class='',width=32,height=16,x=114,y=425,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-353,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='28',objType='LDImage',class='',width=32,height=16,x=146,y=428,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-356,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='29',objType='LDImage',class='',width=32,height=16,x=180,y=428,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-4,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='30',objType='LDImage',class='',width=32,height=16,x=212,y=424,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-10,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='31',objType='LDImage',class='',width=32,height=16,x=245,y=417,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='32',objType='LDImage',class='',width=32,height=16,x=276,y=407,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-21,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='33',objType='LDImage',class='',width=32,height=16,x=305,y=387,xScale=0.5*1,yScale=0.5*1,assetName='B12_12',
		rotation=-49,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='g' },},
		},
	{name='34',objType='LDImage',class='',width=32,height=16,x=153,y=344,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='35',objType='LDImage',class='',width=32,height=16,x=169,y=344,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=270,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='36',objType='LDImage',class='',width=32,height=16,x=149,y=310,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=255,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='37',objType='LDImage',class='',width=32,height=16,x=173,y=311,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=285,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='38',objType='LDImage',class='',width=32,height=16,x=136,y=279,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=240,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='39',objType='LDImage',class='',width=32,height=16,x=186,y=280,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='40',objType='LDImage',class='',width=32,height=16,x=115,y=252,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='41',objType='LDImage',class='',width=32,height=16,x=206,y=253,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='42',objType='LDImage',class='',width=32,height=16,x=89,y=231,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=210,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='43',objType='LDImage',class='',width=32,height=16,x=233,y=232,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=32,height=16,x=130,y=241,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=225,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='45',objType='LDImage',class='',width=24.1221,height=16,x=148,y=264,xScale=0.376907*1,yScale=0.5*1,assetName='B12_23',
		rotation=240,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='46',objType='LDImage',class='',width=32,height=16,x=103,y=220,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=210,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='47',objType='LDImage',class='',width=32,height=16,x=220,y=220,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=330,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='48',objType='LDImage',class='',width=32,height=16,x=193,y=241,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='49',objType='LDImage',class='',width=24.8782,height=16,x=174,y=265,xScale=0.388722*1,yScale=0.5*1,assetName='B12_23',
		rotation=300,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='50',objType='LDImage',class='',width=32,height=16,x=51,y=321,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=74,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='51',objType='LDImage',class='',width=32,height=16,x=47,y=288,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=93,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='52',objType='LDImage',class='',width=32,height=16,x=51,y=255,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=102,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='53',objType='LDImage',class='',width=32,height=16,x=63,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=118,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='54',objType='LDImage',class='',width=32,height=16,x=273,y=289,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=268,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='55',objType='LDImage',class='',width=32,height=16,x=269,y=323,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=286,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='56',objType='LDImage',class='',width=32,height=16,x=269,y=255,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=257,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='57',objType='LDImage',class='',width=32,height=16,x=258,y=223,xScale=0.5*1,yScale=0.5*1,assetName='B12_23',
		rotation=-118,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='58',objType='LDImage',class='',width=32,height=16,x=95,y=311,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_11',
		rotation=45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='59',objType='LDImage',class='',width=32,height=16,x=229,y=312,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_11',
		rotation=-45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

