-- Generated by Level Director X v1.1.0 on mer feb 5 17:55:49 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B12']={}
	assets.spriteSheetData['B12'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B05']={}
	assets.spriteSheetData['B05'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B08']={}
	assets.spriteSheetData['B08'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B11Speciale (2)']={}
	assets.spriteSheetData['B11Speciale (2)'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['B12_12']={file ='B12.png',name='B12_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B12',frameCount=25,
		 }
	assets['B12_17']={file ='B12.png',name='B12_17',class='',aX=0.5,aY=0.5,width=64,height=32,frame=18,spriteSheetName='B12',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B12_18']={file ='B12.png',name='B12_18',class='',aX=0.5,aY=0.5,width=64,height=32,frame=19,spriteSheetName='B12',frameCount=25,
		 }
	assets['B12_19']={file ='B12.png',name='B12_19',class='',aX=0.5,aY=0.5,width=64,height=32,frame=20,spriteSheetName='B12',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B12_24']={file ='B12.png',name='B12_24',class='',aX=0.5,aY=0.5,width=64,height=32,frame=25,spriteSheetName='B12',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B05_0']={file ='B05.png',name='B05_0',class='',aX=0.5,aY=0.5,width=64,height=32,frame=1,spriteSheetName='B05',frameCount=25,
		 }
	assets['B05_18']={file ='B05.png',name='B05_18',class='',aX=0.5,aY=0.5,width=64,height=32,frame=19,spriteSheetName='B05',frameCount=25,
		 }
	assets['egitto5buiona_0']={file ='egitto5buiona.jpg',name='egitto5buiona_0',class='',aX=0.5,aY=0.5,width=306,height=400,frame=0,spriteSheetName='egitto5buiona',frameCount=1,
		 }
	assets['questaaaaa_0']={file ='questaaaaa.jpg',name='questaaaaa_0',class='',aX=0.5,aY=0.5,width=564,height=756,frame=0,spriteSheetName='questaaaaa',frameCount=1,
		 }
	assets['B08_0']={file ='B08.png',name='B08_0',class='',aX=0.5,aY=0.5,width=64,height=32,frame=1,spriteSheetName='B08',frameCount=25,
		 }
	assets['B08_1']={file ='B08.png',name='B08_1',class='',aX=0.5,aY=0.5,width=64,height=32,frame=2,spriteSheetName='B08',frameCount=25,
		 }
	assets['B08_3']={file ='B08.png',name='B08_3',class='',aX=0.5,aY=0.5,width=64,height=32,frame=4,spriteSheetName='B08',frameCount=25,
		 }
	assets['B08_9']={file ='B08.png',name='B08_9',class='',aX=0.5,aY=0.5,width=64,height=32,frame=10,spriteSheetName='B08',frameCount=25,
		 }
	assets['B08_17']={file ='B08.png',name='B08_17',class='',aX=0.5,aY=0.5,width=64,height=32,frame=18,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,32,-16,32,16,-32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_18']={file ='B08.png',name='B08_18',class='',aX=0.5,aY=0.5,width=64,height=32,frame=19,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,32,-16,32,16,-32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_19']={file ='B08.png',name='B08_19',class='',aX=0.5,aY=0.5,width=64,height=32,frame=20,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,32,-16,32,16,-32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B08_21']={file ='B08.png',name='B08_21',class='',aX=0.5,aY=0.5,width=64,height=32,frame=22,spriteSheetName='B08',frameCount=25,
		 }
	assets['B08_24']={file ='B08.png',name='B08_24',class='',aX=0.5,aY=0.5,width=64,height=32,frame=25,spriteSheetName='B08',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='kinematic',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,32,-16,32,16,-32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B11Speciale (2)_1']={file ='B11Speciale (2).png',name='B11Speciale (2)_1',class='',aX=0.5,aY=0.5,width=64,height=32,frame=2,spriteSheetName='B11Speciale (2)',frameCount=25,
		 }
	assets['B11Speciale (2)_21']={file ='B11Speciale (2).png',name='B11Speciale (2)_21',class='',aX=0.5,aY=0.5,width=64,height=32,frame=22,spriteSheetName='B11Speciale (2)',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,32,-16,32,16,-32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level04' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='questaaaaa_0',objType='LDImage',class='',width=320,height=456,x=160,y=228,xScale=0.567376*1,yScale=0.603175*1,assetName='questaaaaa_0',
		userProps = {},
		},
	{name='a1',objType='LDImage',class='',width=58.7437,height=11.7649,x=75,y=197,xScale=0.91787*1,yScale=0.367653*1,assetName='B12_24',
		rotation=31,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a2',objType='LDImage',class='',width=58.7437,height=11.7649,x=64,y=255,xScale=0.91787*1,yScale=0.367653*1,assetName='B12_24',
		rotation=31,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a3',objType='LDImage',class='',width=33.0966,height=18.8963,x=252,y=250,xScale=0.517134*1,yScale=0.590509*1,assetName='B12_19',
		rotation=52,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a4',objType='LDImage',class='',width=33.0966,height=18.8963,x=276,y=278,xScale=0.517134*1,yScale=0.590509*1,assetName='B12_19',
		rotation=47,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a5',objType='LDImage',class='',width=33.0966,height=18.8963,x=300,y=305,xScale=0.517134*1,yScale=0.590509*1,assetName='B12_19',
		rotation=46,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a6',objType='LDImage',class='',width=42.6667,height=9.33333,x=66,y=362,xScale=0.666667*1,yScale=0.291667*1,assetName='B12_17',
		userProps = {},
		},
	{name='a7',objType='LDImage',class='',width=42.6667,height=9.33333,x=248,y=362,xScale=0.666667*1,yScale=0.291667*1,assetName='B12_17',
		userProps = {},
		},
	{name='a8',objType='LDImage',class='',width=34.0075,height=17.2815,x=64,y=143,xScale=0.531367*1,yScale=0.540047*1,assetName='B08_18',
		rotation=-339,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a9',objType='LDImage',class='',width=35,height=17.2815,x=101,y=156,xScale=0.546875*1,yScale=0.540047*1,assetName='B08_18',
		rotation=-344,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a10',objType='LDImage',class='',width=34.2482,height=17.2815,x=139,y=166,xScale=0.535128*1,yScale=0.540047*1,assetName='B08_18',
		rotation=-347,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a11',objType='LDImage',class='',width=35,height=16,x=179,y=174,xScale=0.546875*1,yScale=0.5*1,assetName='B08_18',
		rotation=-353,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a12',objType='LDImage',class='',width=35,height=16,x=218,y=180,xScale=0.546875*1,yScale=0.5*1,assetName='B08_18',
		rotation=-356,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a13',objType='LDImage',class='',width=35,height=16,x=258,y=225,xScale=0.546875*1,yScale=0.5*1,assetName='B08_18',
		rotation=-19,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a14',objType='LDImage',class='',width=35,height=16,x=294,y=210,xScale=0.546875*1,yScale=0.5*1,assetName='B08_18',
		rotation=-26,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a15',objType='LDImage',class='',width=35,height=16,x=218,y=235,xScale=0.546875*1,yScale=0.5*1,assetName='B08_18',
		rotation=-13,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a16',objType='LDImage',class='',width=52.8241,height=16,x=108,y=303,xScale=0.825377*1,yScale=0.5*1,assetName='B08_18',
		userProps = {},
		},
	{name='a17',objType='LDImage',class='',width=58.742,height=16,x=204,y=301,xScale=0.917844*1,yScale=0.5*1,assetName='B08_18',
		userProps = {},
		},
	{name='a18',objType='LDImage',class='',width=46,height=14,x=156,y=325,xScale=0.71875*1,yScale=0.4375*1,assetName='B08_18',
		userProps = {},
		},
	{name='a19',objType='LDImage',class='',width=51.6667,height=14,x=154,y=345,xScale=0.807292*1,yScale=0.4375*1,assetName='B08_18',
		userProps = {},
		},
	{name='a20',objType='LDImage',class='',width=61,height=14,x=154,y=365,xScale=0.953125*1,yScale=0.4375*1,assetName='B08_18',
		userProps = {},
		},
	{name='a21',objType='LDImage',class='',width=69.6667,height=14,x=153,y=382,xScale=1.08854*1,yScale=0.4375*1,assetName='B08_18',
		userProps = {},
		},
	{name='a22',objType='LDImage',class='',width=36,height=16,x=155,y=304,xScale=0.5625*1,yScale=0.5*1,assetName='B11Speciale (2)_21',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='a23',objType='LDImage',class='',width=25.1923,height=11.9809,x=31,y=148,xScale=0.39363*1,yScale=0.374403*1,assetName='B08_17',
		rotation=295,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a24',objType='LDImage',class='',width=25.1923,height=11.9809,x=20,y=174,xScale=0.39363*1,yScale=0.374403*1,assetName='B08_17',
		rotation=294,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a25',objType='LDImage',class='',width=25.1923,height=11.9809,x=8,y=200,xScale=0.39363*1,yScale=0.374403*1,assetName='B08_17',
		rotation=294,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='a26',objType='LDImage',class='',width=35,height=16,x=25,y=126,xScale=0.546875*1,yScale=0.5*1,assetName='B08_18',
		rotation=-332,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

