-- Generated by Level Director X v1.1.0 on gio gen 30 19:47:10 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B03']={}
	assets.spriteSheetData['B03'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['25238fb7c09d88023911b31ed00a83d0_0']={file ='25238fb7c09d88023911b31ed00a83d0.jpg',name='25238fb7c09d88023911b31ed00a83d0_0',class='',aX=0.5,aY=0.5,width=564,height=1128,frame=0,spriteSheetName='25238fb7c09d88023911b31ed00a83d0',frameCount=1,
		 }
	assets['B11Speciale_4']={file ='B11Speciale.png',name='B11Speciale_4',class='',aX=0.5,aY=0.5,width=64,height=32,frame=5,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_4']={file ='B03.png',name='B03_4',class='',aX=0.5,aY=0.5,width=64,height=32,frame=5,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_8']={file ='B03.png',name='B03_8',class='',aX=0.5,aY=0.5,width=64,height=32,frame=9,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_13']={file ='B03.png',name='B03_13',class='',aX=0.5,aY=0.5,width=64,height=32,frame=14,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B03_23']={file ='B03.png',name='B03_23',class='',aX=0.5,aY=0.5,width=64,height=32,frame=24,spriteSheetName='B03',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={-32,-16,-32,16,32,16,32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level05' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='25238fb7c09d88023911b31ed00a83d0_0',objType='LDImage',class='',width=320,height=610,x=160,y=232,xScale=0.567376*1,yScale=0.54078*1,assetName='25238fb7c09d88023911b31ed00a83d0_0',
		userProps = {},
		},
	{name='1',objType='LDImage',class='',width=32,height=16,x=285,y=234,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_4',
		rotation=-45,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='2',objType='LDImage',class='',width=32,height=16,x=18,y=293,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='3',objType='LDImage',class='',width=32,height=16,x=50,y=310,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='4',objType='LDImage',class='',width=32,height=16,x=82,y=326,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='5',objType='LDImage',class='',width=32,height=16,x=114,y=342,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='6',objType='LDImage',class='',width=32,height=16,x=18,y=278,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='7',objType='LDImage',class='',width=32,height=16,x=50,y=294,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='8',objType='LDImage',class='',width=32,height=16,x=82,y=310,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='9',objType='LDImage',class='',width=32,height=16,x=114,y=326,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='10',objType='LDImage',class='',width=32,height=16,x=146,y=342,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='11',objType='LDImage',class='',width=32,height=16,x=146,y=326,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='12',objType='LDImage',class='',width=32,height=16,x=178,y=342,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='13',objType='LDImage',class='',width=32,height=16,x=178,y=326,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='14',objType='LDImage',class='',width=32,height=16,x=210,y=342,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='15',objType='LDImage',class='',width=32,height=16,x=210,y=326,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='16',objType='LDImage',class='',width=32,height=16,x=136,y=301,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='17',objType='LDImage',class='',width=32,height=16,x=159,y=278,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='18',objType='LDImage',class='',width=32,height=16,x=204,y=231,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='19',objType='LDImage',class='',width=32,height=16,x=182,y=255,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='20',objType='LDImage',class='',width=32,height=16,x=272,y=162,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='21',objType='LDImage',class='',width=32,height=16,x=227,y=209,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='22',objType='LDImage',class='',width=32,height=16,x=250,y=185,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='23',objType='LDImage',class='',width=32,height=16,x=228,y=231,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='24',objType='LDImage',class='',width=32,height=16,x=296,y=162,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='25',objType='LDImage',class='',width=32,height=16,x=183,y=277,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='26',objType='LDImage',class='',width=32,height=16,x=160,y=300,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='27',objType='LDImage',class='',width=32,height=16,x=206,y=254,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='28',objType='LDImage',class='',width=32,height=16,x=251,y=208,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='29',objType='LDImage',class='',width=32,height=16,x=274,y=185,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='30',objType='LDImage',class='',width=32,height=16,x=18,y=262,xScale=0.5*1,yScale=0.5*1,assetName='B03_23',
		userProps = {},
		},
	{name='31',objType='LDImage',class='',width=32,height=16,x=18,y=245,xScale=0.5*1,yScale=0.5*1,assetName='B03_23',
		userProps = {},
		},
	{name='32',objType='LDImage',class='',width=32,height=16,x=18,y=213,xScale=0.5*1,yScale=0.5*1,assetName='B03_23',
		userProps = {},
		},
	{name='33',objType='LDImage',class='',width=32,height=16,x=18,y=229,xScale=0.5*1,yScale=0.5*1,assetName='B03_23',
		userProps = {},
		},
	{name='34',objType='LDImage',class='',width=32,height=16,x=18,y=180,xScale=0.5*1,yScale=0.5*1,assetName='B03_23',
		userProps = {},
		},
	{name='35',objType='LDImage',class='',width=32,height=16,x=18,y=197,xScale=0.5*1,yScale=0.5*1,assetName='B03_23',
		userProps = {},
		},
	{name='36',objType='LDImage',class='',width=32,height=16,x=18,y=164,xScale=0.5*1,yScale=0.5*1,assetName='B03_23',
		userProps = {},
		},
	{name='37',objType='LDImage',class='',width=32,height=16,x=18,y=147,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		userProps = {},
		},
	{name='38',objType='LDImage',class='',width=32,height=16,x=295,y=139,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		rotation=315,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {{name= 'vita', value='1' },},
		},
	{name='39',objType='LDImage',class='',width=32,height=16,x=243,y=326,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='40',objType='LDImage',class='',width=32,height=16,x=243,y=310,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='41',objType='LDImage',class='',width=32,height=16,x=275,y=310,xScale=0.5*1,yScale=0.5*1,assetName='B03_13',
		userProps = {},
		},
	{name='42',objType='LDImage',class='',width=32,height=16,x=275,y=294,xScale=0.5*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='43',objType='LDImage',class='',width=32,height=16,x=18,y=131,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		userProps = {},
		},
	{name='44',objType='LDImage',class='',width=32,height=16,x=18,y=114,xScale=0.5*1,yScale=0.5*1,assetName='B03_4',
		userProps = {},
		},
	{name='45',objType='LDImage',class='',width=28.1667,height=16,x=305,y=294,xScale=0.440104*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	{name='46',objType='LDImage',class='',width=28.1667,height=16,x=305,y=310,xScale=0.440105*1,yScale=0.5*1,assetName='B03_8',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

