-- Generated by Level Director X v1.1.0 on mar feb 11 01:43:02 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['static part ui']={}
	assets.spriteSheetData['static part ui'].frames ={
		{x=0,y=0,width=640,height=480},
		{x=0,y=480,width=640,height=480},
		sheetContentWidth=640,
		sheetContentHeight=960
	}
	assets.spriteSheetData['B10']={}
	assets.spriteSheetData['B10'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets.spriteSheetData['B11Speciale']={}
	assets.spriteSheetData['B11Speciale'].frames ={
		{x=0,y=0,width=64,height=32},
		{x=64,y=0,width=64,height=32},
		{x=128,y=0,width=64,height=32},
		{x=192,y=0,width=64,height=32},
		{x=256,y=0,width=64,height=32},
		{x=0,y=32,width=64,height=32},
		{x=64,y=32,width=64,height=32},
		{x=128,y=32,width=64,height=32},
		{x=192,y=32,width=64,height=32},
		{x=256,y=32,width=64,height=32},
		{x=0,y=64,width=64,height=32},
		{x=64,y=64,width=64,height=32},
		{x=128,y=64,width=64,height=32},
		{x=192,y=64,width=64,height=32},
		{x=256,y=64,width=64,height=32},
		{x=0,y=96,width=64,height=32},
		{x=64,y=96,width=64,height=32},
		{x=128,y=96,width=64,height=32},
		{x=192,y=96,width=64,height=32},
		{x=256,y=96,width=64,height=32},
		{x=0,y=128,width=64,height=32},
		{x=64,y=128,width=64,height=32},
		{x=128,y=128,width=64,height=32},
		{x=192,y=128,width=64,height=32},
		{x=256,y=128,width=64,height=32},
		sheetContentWidth=320,
		sheetContentHeight=160
	}
	assets['natura3_0']={file ='natura3.jpg',name='natura3_0',class='',aX=0.5,aY=0.5,width=564,height=783,frame=0,spriteSheetName='natura3',frameCount=1,
		 }
	assets['static part ui_0']={file ='static part ui.png',name='static part ui_0',class='',aX=0.5,aY=0.5,width=640,height=960,frame=0,spriteSheetName='static part ui',frameCount=1,
		 }
	assets['static part ui_0']={file ='static part ui.png',name='static part ui_0',class='',aX=0.5,aY=0.5,width=640,height=480,frame=1,spriteSheetName='static part ui',frameCount=2,
		 }
	assets['static part ui_1']={file ='static part ui.png',name='static part ui_1',class='',aX=0.5,aY=0.5,width=640,height=480,frame=2,spriteSheetName='static part ui',frameCount=2,
		 }
	assets['B10_3']={file ='B10.png',name='B10_3',class='',aX=0.5,aY=0.5,width=64,height=32,frame=4,spriteSheetName='B10',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B10_8']={file ='B10.png',name='B10_8',class='',aX=0.5,aY=0.5,width=64,height=32,frame=9,spriteSheetName='B10',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B10_10']={file ='B10.png',name='B10_10',class='',aX=0.5,aY=0.5,width=64,height=32,frame=11,spriteSheetName='B10',frameCount=25,
		 }
	assets['B10_12']={file ='B10.png',name='B10_12',class='',aX=0.5,aY=0.5,width=64,height=32,frame=13,spriteSheetName='B10',frameCount=25,
		 }
	assets['B10_14']={file ='B10.png',name='B10_14',class='',aX=0.5,aY=0.5,width=64,height=32,frame=15,spriteSheetName='B10',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B10_15']={file ='B10.png',name='B10_15',class='',aX=0.5,aY=0.5,width=64,height=32,frame=16,spriteSheetName='B10',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,-32,-16,-32,16,32,16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B10_16']={file ='B10.png',name='B10_16',class='',aX=0.5,aY=0.5,width=64,height=32,frame=17,spriteSheetName='B10',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B10_20']={file ='B10.png',name='B10_20',class='',aX=0.5,aY=0.5,width=64,height=32,frame=21,spriteSheetName='B10',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B11Speciale_10']={file ='B11Speciale.png',name='B11Speciale_10',class='',aX=0.5,aY=0.5,width=64,height=32,frame=11,spriteSheetName='B11Speciale',frameCount=25,
		tipo='speciale',		
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['B11Speciale_15']={file ='B11Speciale.png',name='B11Speciale_15',class='',aX=0.5,aY=0.5,width=64,height=32,frame=16,spriteSheetName='B11Speciale',frameCount=25,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,linearDamping=0,angularDamping=0,gravityScale=1,isBullet=false,shapes={{bodyShape='Polygon',shape={32,-16,32,16,-32,16,-32,-16},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level03' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- Layer 1 ------------------------------------------------------------------------------------
	level.layers['Layer 1']={} 
	level.layers['Layer 1'].view=display.newGroup() 
	level.layers['Layer 1'].name='Layer 1' 
	if (level.parallaxEnabled) then
		level.layers['Layer 1'].speed={x=0,y=0}
		level.layers['Layer 1'].repeated=false
		level.layers['Layer 1'].cullingMethod=0
	else
		level.layers['Layer 1'].cullingMethod=0 
	end
	level.layers['Layer 1'].objects={} 
	objects = {
	{name='natura3_0',objType='LDImage',class='',width=320,height=480,x=160,y=240,xScale=0.567376*1,yScale=0.613027*1,assetName='natura3_0',
		userProps = {},
		},
	{name='B10_9',objType='LDImage',class='',width=32,height=16,x=31,y=221,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=-28,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_10',objType='LDImage',class='',width=32,height=16,x=50,y=198,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=15,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_11',objType='LDImage',class='',width=32,height=16,x=74,y=183,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=30,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_14',objType='LDImage',class='',width=32,height=16,x=67,y=150,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=332,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_15',objType='LDImage',class='',width=32,height=16,x=194,y=186,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=14,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_16',objType='LDImage',class='',width=32,height=16,x=66,y=281,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=-43,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_17',objType='LDImage',class='',width=32,height=16,x=39,y=269,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=-28,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_18',objType='LDImage',class='',width=32,height=16,x=27,y=113,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=318,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_19',objType='LDImage',class='',width=32,height=16,x=236,y=178,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=288,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_20',objType='LDImage',class='',width=32,height=16,x=33,y=140,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=303,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_22',objType='LDImage',class='',width=32,height=16,x=33,y=173,xScale=0.5*1,yScale=0.5*1,assetName='B10_16',
		rotation=-56,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_23',objType='LDImage',class='',width=32,height=16,x=75,y=124,xScale=0.5*1,yScale=0.5*1,assetName='B10_16',
		rotation=-10,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_24',objType='LDImage',class='',width=32,height=16,x=33,y=243,xScale=0.5*1,yScale=0.5*1,assetName='B10_16',
		rotation=-74,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_25',objType='LDImage',class='',width=32,height=16,x=30,y=289,xScale=0.5*1,yScale=0.5*1,assetName='B10_16',
		rotation=-31,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_29',objType='LDImage',class='',width=32,height=16,x=245,y=147,xScale=0.5*1,yScale=0.5*1,assetName='B10_16',
		rotation=-7,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_30',objType='LDImage',class='',width=32,height=16,x=213,y=195,xScale=0.5*1,yScale=0.5*1,assetName='B10_16',
		rotation=-10,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_31',objType='LDImage',class='',width=32,height=16,x=152,y=222,xScale=0.5*1,yScale=0.5*1,assetName='B10_20',
		userProps = {{name= 'tipo', value='unbreak' },},
		},
	{name='B10_28',objType='LDImage',class='',width=32,height=16,x=77,y=236,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_15',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	{name='B10_8',objType='LDImage',class='',width=32,height=16,x=203,y=256,xScale=0.5*1,yScale=0.5*1,assetName='B10_8',
		userProps = {},
		},
	{name='B10_32',objType='LDImage',class='',width=32,height=16,x=268,y=256,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		userProps = {},
		},
	{name='B10_34',objType='LDImage',class='',width=32,height=16,x=128,y=263,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		rotation=70,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_35',objType='LDImage',class='',width=32,height=16,x=208,y=327,xScale=0.5*1,yScale=0.5*1,assetName='B10_8',
		userProps = {},
		},
	{name='B10_36',objType='LDImage',class='',width=32,height=16,x=235,y=256,xScale=0.5*1,yScale=0.5*1,assetName='B10_8',
		userProps = {},
		},
	{name='B10_37',objType='LDImage',class='',width=32,height=16,x=282,y=273,xScale=0.5*1,yScale=0.5*1,assetName='B10_8',
		userProps = {},
		},
	{name='B10_38',objType='LDImage',class='',width=32,height=16,x=304,y=327,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		userProps = {},
		},
	{name='B10_39',objType='LDImage',class='',width=32,height=16,x=301,y=256,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		userProps = {},
		},
	{name='B10_40',objType='LDImage',class='',width=32,height=16,x=16,y=335,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		rotation=61,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_41',objType='LDImage',class='',width=32,height=16,x=39,y=363,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		rotation=-337,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_42',objType='LDImage',class='',width=32,height=16,x=240,y=327,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		userProps = {},
		},
	{name='B10_43',objType='LDImage',class='',width=32,height=16,x=256,y=343,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		userProps = {},
		},
	{name='B10_44',objType='LDImage',class='',width=32,height=16,x=218,y=273,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		userProps = {},
		},
	{name='B10_45',objType='LDImage',class='',width=32,height=16,x=277,y=173,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=21,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_46',objType='LDImage',class='',width=32,height=16,x=282,y=120,xScale=0.5*1,yScale=0.5*1,assetName='B10_16',
		rotation=-10,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_47',objType='LDImage',class='',width=32,height=16,x=297,y=129,xScale=0.5*1,yScale=0.5*1,assetName='B10_3',
		rotation=334,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_12',objType='LDImage',class='',width=32,height=16,x=290,y=183,xScale=0.5*1,yScale=0.5*1,assetName='B10_16',
		rotation=-10,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_26',objType='LDImage',class='',width=32,height=16,x=294,y=148,xScale=0.5*1,yScale=0.5*1,assetName='B10_15',
		rotation=358,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_33',objType='LDImage',class='',width=32,height=16,x=261,y=205,xScale=0.5*1,yScale=0.5*1,assetName='B10_15',
		rotation=89,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_48',objType='LDImage',class='',width=32,height=16,x=272,y=327,xScale=0.5*1,yScale=0.5*1,assetName='B10_8',
		userProps = {},
		},
	{name='B10_27',objType='LDImage',class='',width=32,height=16,x=143,y=297,xScale=0.5*1,yScale=0.5*1,assetName='B10_8',
		rotation=60,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_21',objType='LDImage',class='',width=32,height=16,x=172,y=319,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		rotation=23,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_7',objType='LDImage',class='',width=32,height=16,x=42,y=337,xScale=0.5*1,yScale=0.5*1,assetName='B10_14',
		rotation=41,enableDrag=false,anchorX=0.5,anchorY=0.5,alpha=1,isVisible=true,blendMode='normal',
		userProps = {},
		},
	{name='B10_13',objType='LDImage',class='',width=32,height=16,x=250,y=282,xScale=0.5*1,yScale=0.5*1,assetName='B11Speciale_10',
		userProps = {{name= 'tipo', value='speciale' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['Layer 1'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['Layer 1'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

