-- Generated by Level Director X v1.1.0 on dom gen 12 16:52:46 2020 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['b']={}
	assets.spriteSheetData['b'].frames ={
		{x=1,y=1,width=470,height=472},
		{x=473,y=1,width=470,height=472},
		{x=945,y=1,width=470,height=472},
		{x=1417,y=1,width=470,height=472},
		{x=1,y=475,width=470,height=472},
		{x=473,y=475,width=470,height=472},
		{x=945,y=475,width=470,height=472},
		{x=1417,y=475,width=470,height=472},
		{x=1,y=949,width=470,height=472},
		{x=473,y=949,width=470,height=472},
		{x=945,y=949,width=470,height=472},
		{x=1417,y=949,width=470,height=472},
		{x=1,y=1423,width=470,height=472},
		{x=473,y=1423,width=470,height=472},
		{x=945,y=1423,width=470,height=472},
		{x=1417,y=1423,width=470,height=472},
		sheetContentWidth=1888,
		sheetContentHeight=1896
	}
	assets.spriteSheetData['crimsonWalk']={}
	assets.spriteSheetData['crimsonWalk'].frames ={
		{x=0,y=0,width=700,height=500},
		{x=700,y=0,width=700,height=500},
		{x=1400,y=0,width=700,height=500},
		{x=2100,y=0,width=700,height=500},
		{x=2800,y=0,width=700,height=500},
		{x=0,y=500,width=700,height=500},
		{x=700,y=500,width=700,height=500},
		{x=1400,y=500,width=700,height=500},
		{x=2100,y=500,width=700,height=500},
		{x=2800,y=500,width=700,height=500},
		{x=0,y=1000,width=700,height=500},
		{x=700,y=1000,width=700,height=500},
		{x=1400,y=1000,width=700,height=500},
		{x=2100,y=1000,width=700,height=500},
		{x=2800,y=1000,width=700,height=500},
		{x=0,y=1500,width=700,height=500},
		{x=700,y=1500,width=700,height=500},
		{x=1400,y=1500,width=700,height=500},
		{x=2100,y=1500,width=700,height=500},
		{x=2800,y=1500,width=700,height=500},
		sheetContentWidth=3500,
		sheetContentHeight=2000
	}
	assets['wall_0']={file ='wallPGs.png',name='wall_0',class='',aX=0.5,aY=0.5,width=320,height=480,frame=0,spriteSheetName='wall',frameCount=1,
		 }
	assets['b_1']={file ='batuffolo.png',name='b_1',class='',aX=0.5,aY=0.5,width=470,height=472,frame=2,spriteSheetName='b',frameCount=16,
		sequenceData={{name='colorfull',frames={ 2,3,1,4,6,10,14,7,8,11,15,5,9,13 },time =1200,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='colorfull',play=false },
		 }
	assets['scroll-b_0']={file ='scroll-cottonBall.png',name='scroll-b_0',class='',aX=0.5,aY=0.5,width=400,height=400,frame=0,spriteSheetName='scroll-b',frameCount=1,
		 }
	assets['back_0']={file ='back.png',name='back_0',class='',aX=0.5,aY=0.5,width=200,height=200,frame=0,spriteSheetName='back',frameCount=1,
		 }
	assets['scroll-crimson_0']={file ='scroll-crimson.png',name='scroll-crimson_0',class='',aX=0.5,aY=0.5,width=400,height=400,frame=0,spriteSheetName='scroll-crimson',frameCount=1,
		 }
	assets['crimsonWalk_4']={file ='crimsonWalk.png',name='crimsonWalk_4',class='',aX=0.5,aY=0.5,width=700,height=500,frame=5,spriteSheetName='crimsonWalk',frameCount=20,
		sequenceData={{name='walking',frames={ 5,6,7,8,9,10,11,12,13,14,15,16,17,18,1,2,3,4 },time =1000,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='walking',play=false },
		 }
	assets['notAvailable_0']={file ='notAvailable.png',name='notAvailable_0',class='',aX=0.5,aY=0.5,width=200,height=200,frame=0,spriteSheetName='notAvailable',frameCount=1,
		 }
	assets['sky_0']={file ='sky.png',name='sky_0',class='',aX=0.5,aY=0.5,width=320,height=256,frame=0,spriteSheetName='sky',frameCount=1,
		 }
	assets['landScape_0']={file ='landScape.jpg',name='landScape_0',class='',aX=0.5,aY=0.5,width=640,height=486,frame=0,spriteSheetName='landScape',frameCount=1,
		 }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	local k=0
	local objects = nil 
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',102/255,102/255,102/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='sceltaPersonaggio' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=false
	-- Layers --
	level.layers={} 
	---- backgrounds ------------------------------------------------------------------------------------
	level.layers['backgrounds']={} 
	level.layers['backgrounds'].view=display.newGroup() 
	level.layers['backgrounds'].name='backgrounds' 
	if (level.parallaxEnabled) then
		level.layers['backgrounds'].speed={x=0,y=0}
		level.layers['backgrounds'].repeated=false
		level.layers['backgrounds'].cullingMethod=0
	else
		level.layers['backgrounds'].cullingMethod=0 
	end
	level.layers['backgrounds'].objects={} 
	objects = {
	{name='rect_pg4',objType='LDRectangle',class='',width=125.25,height=189.25,x=241,y=358,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=62.625,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=49/255,fillColorG=49/255,fillColorB=49/255,fillColorA=255/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=49/255,fillColorG=49/255,fillColorB=49/255,fillColorA=255/255},
		userProps = {{name= 'pgName', value='' },},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=true,isBullet=false,linearDamping=0,angularDamping=0,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
		},
	{name='rect_pg3',objType='LDRectangle',class='',width=130.625,height=188.375,x=81,y=359,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=65.3125,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=49/255,fillColorG=49/255,fillColorB=49/255,fillColorA=255/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=49/255,fillColorG=49/255,fillColorB=49/255,fillColorA=255/255},
		userProps = {{name= 'pgName', value='' },},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=true,isBullet=false,linearDamping=0,angularDamping=0,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
		},
	{name='rect_pg1',objType='LDImage',class='',width=134,height=166,x=80,y=116,xScale=0.41875*1,yScale=0.648438*1,assetName='sky_0',
		userProps = {{name= 'pgName', value='cottonBall' },},
		},
	{name='rect_pg2',objType='LDImage',class='',width=145,height=181.946,x=239,y=110,xScale=0.226562*1,yScale=0.374374*1,assetName='landScape_0',
		userProps = {{name= 'pgName', value='crimson' },},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['backgrounds'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['backgrounds'])
	---- wallPGs ------------------------------------------------------------------------------------
	level.layers['wallPGs']={} 
	level.layers['wallPGs'].view=display.newGroup() 
	level.layers['wallPGs'].name='wallPGs' 
	if (level.parallaxEnabled) then
		level.layers['wallPGs'].speed={x=0,y=0}
		level.layers['wallPGs'].repeated=false
		level.layers['wallPGs'].cullingMethod=0
	else
		level.layers['wallPGs'].cullingMethod=0 
	end
	level.layers['wallPGs'].objects={} 
	objects = {
	{name='wall_0',objType='LDImage',class='',width=320,height=480,x=160,y=240,xScale=1*1,yScale=1*1,assetName='wall_0',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['wallPGs'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['wallPGs'])
	---- PGs ------------------------------------------------------------------------------------
	level.layers['PGs']={} 
	level.layers['PGs'].view=display.newGroup() 
	level.layers['PGs'].name='PGs' 
	if (level.parallaxEnabled) then
		level.layers['PGs'].speed={x=0,y=0}
		level.layers['PGs'].repeated=false
		level.layers['PGs'].cullingMethod=0
	else
		level.layers['PGs'].cullingMethod=0 
	end
	level.layers['PGs'].objects={} 
	objects = {
	{name='cottonBall',objType='LDImage',class='',width=141,height=138.5,x=80,y=99,xScale=0.3*1,yScale=0.293432*1,assetName='b_1',
		userProps = {},
		},
	{name='scroll-b_0',objType='LDImage',class='',width=222.5,height=237.5,x=84,y=194,xScale=0.55625*1,yScale=0.59375*1,assetName='scroll-b_0',
		userProps = {},
		},
	{name='scroll-crimson_0',objType='LDImage',class='',width=222,height=237,x=239,y=194,xScale=0.555*1,yScale=0.5925*1,assetName='scroll-crimson_0',
		userProps = {},
		},
	{name='crimson',objType='LDImage',class='',width=241,height=172.143,x=238,y=117,xScale=0.344286*1,yScale=0.344286*1,assetName='crimsonWalk_4',
		userProps = {},
		},
	{name='notAvailable_0',objType='LDImage',class='',width=96,height=96,x=80,y=362,xScale=0.48*1,yScale=0.48*1,assetName='notAvailable_0',
		userProps = {},
		},
	{name='notAvailable_6',objType='LDImage',class='',width=96,height=96,x=240,y=362,xScale=0.48*1,yScale=0.48*1,assetName='notAvailable_0',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['PGs'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['PGs'])
	---- ui ------------------------------------------------------------------------------------
	level.layers['ui']={} 
	level.layers['ui'].view=display.newGroup() 
	level.layers['ui'].name='ui' 
	if (level.parallaxEnabled) then
		level.layers['ui'].speed={x=0,y=0}
		level.layers['ui'].repeated=false
		level.layers['ui'].cullingMethod=0
	else
		level.layers['ui'].cullingMethod=0 
	end
	level.layers['ui'].objects={} 
	objects = {
	{name='back_0',objType='LDImage',class='',width=41,height=31.5,x=296,y=461,xScale=0.205*1,yScale=0.1575*1,assetName='back_0',
		userProps = {},
		},
	}
	-- add objects to layer
	for k, objProps in pairs (objects) do
		obj = instance:createObject(level.layers['ui'], objProps ,level.assets)
		if (obj and objProps.userProps) then
			obj.property = {}
			for u, userProp in pairs (objProps.userProps) do
				obj.property[userProp.name] = userProp.value 
			end 
		end 
	end
	instance:insertLayer(level,level.layers['ui'])
	--level.ldVersion=1.1.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=320
	level.canvasHeight=480
	if level.parallaxEnabled then
		level.parallaxInfinite=false
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

